### ISSUE TITLE
ktlint integration in detekt

### ISSUE THREAD

**Issue by Mauin** [detekt/detekt#1304]
Seen this question come up in multiple Issues now, so creating this to keep the discussion together.

**Comment by Mauin** [comment]
Points from @vanniktech 

> [...] this wrapping functionality from Detekt shouldn't even exist in the first place.

**Comment by Mauin** [comment]
From @arturbosch 

>Maybe its confusing that the default detekt config was the formatting rule set in it while it still needs the formatting jar ...
>
>@vanniktech maybe it is your opinion. But actually it makes sense to wrap ktlint rules:
>
> 1) do not recreate the expensive KotlinCoreEnvironment for KtLint
> 2) have ktlint warnings integrated into sonar-kotlin or other tools like codacy (and private tools) without >writing the integration itself.
> 3) not having configuration options in ktlint is actually a deal breaker for many users, see ktlints issue tracker
>
>Number 1. is actually huge. most detekt users just use the gradle plugin. Each task per module needs the >~500-800ms creation overhead of the KotlinCoreEnvironment. And thats just for 20k lines.

**Comment by vanniktech** [comment]
Let me reason why. I know no other static code analysis tool that wraps others. None of the following do it:

- ErrorProne
- Checkstyle
- ktlint
- PMD
- Findbugs
- Android Lint

Why does Detekt need to wrap ktlint? We always need to update and match with the latest features of ktlint.

Let ktlint handle formatting and styling. Let Detekt do static analysis.

They should be separate tools and not mingle with each other.

**Comment by Mauin** [comment]
I agree with the overall point that the `detekt-formatting` requiring an additional `detektPlugins` jar is quite confusing. And it leads to additional issues we have to triage and handle. As well as possible issues that we have to forward to ktlint. That's not a problem in itself and we can do that, but it increases our workload.

As static analysis tools both detekt and ktlint probably mostly run on CI where the time it takes to run things does not matter as much. If you look at some Bytecode Analyzers or other Static Analysis tools for other languages they can take a looong looong time. But as part of CI builds (imo) build times matter less.

For @arturboschs' third point: That's actually something we should talk to the ktlint maintainers about. They don't allow for much configuration for a reason. I know detekt is on the other end of the spectrum and we're happy to allow as much configuration as required. Wrapping ktlint for convenience (not having to run two tools, even if that is not a big deal at all as ktlint is also very easy to setup by itself) is one thing, but changing the philosophy of ktlint to ours I find a bit weird.

**Comment by schalkms** [comment]
As I see it there are people actually using the ktlint integration in detekt. (myself included)
I am not a big fan of dropping features because some people don't like it, which is fine by the way. However, they don't have to use it and can choose whether they want to enable or disable it. Furthermore, someone (in this case mainly @arturbosch) invested some time in this feature and it clearly brings a benefit to some users of detekt. 

There's always room for improvement, as it's the case with detekt's ktlint integration. I mainly agree with @Mauin that requiring an additional jar for the `formatting` is a bit weird. This might need to change in the future.

Regarding the integration of other static code analysis tools I think that it makes sense to have everything in one config. *Sonar* for instance also has their one rules and integrates detekt nicely.

**Comment by schalkms** [comment]
Regarding the workload for maintaining features I think that this will always be the case as long as detekt's feature list and user base grows. Fortunately, the contributors count and the 3rd party contributions also increased lately, which is one thing I'm really happy about.

**Comment by arturbosch** [comment]
Just because I have invested some time into wrapping KtLint doesn't mean, it has to stay. I'm one of the first guys who would drop features or delete code if there is no demand for it. So not that a big deal ;).

@schalkms has good points:
1. sonar is the most successful tool static analysis tool I know + it integrates detekt findings. It supports many languages and integrates many tools. For example it had checkstyle, pmd and findbugs integrated. Later they rewrote everything to just create one time an AST. Which brings us to number two - performance.

2. Yes we are an open source project and our PR are merged within ~2-5 days. We wait for at least two reviews and there is plenty of time left to wait for the CI. However at my work we also write analysis tool. Heavy analysis which can take 1-4 hours depending on the amount of PRs. Often I work on 2-3 tickets at the same time to wait for CI (yes C++ build time is also huge and automotive industry needs that hard standard).
I get sometimes feedback on slack that detekt runs super fast which is great for them. They talk about 200k lines of code and 30 seconds detekt run compared to 10 minutes of other tools (true story here(type and symbol solving could increase the runtime)). And we do not actually take performance so serious -> visiting each KtFile times the amount of rules -> huge improvement factor for later (for now creating the KotlinEnvironment + loading 1/8 of intellij is slow ;)).

3. Most tools allow to write custom rules. `detekt-formatting` is just a bunch of custom rules which anybody could have written. The difference is, it's in this repo. The maintainance is quite low. I wrote the wrapping in april and the amount of touching the code can be counted with one hand if you exclude my initial commits (`FormattingRule`)

4. Many people use formatting and they like it.

**Comment by 3flex** [comment]
> it increases our workload

I think this is a good enough reason not to wrap ktlint. Each tool should focus on its own strengths. There's plenty of other work to be done on detekt and a long backlog of issues without having to triage ktlint bugs and relay to ktlint if they're found to sit in ktlint rather than detekt.

> changing the philosophy of ktlint to ours I find a bit weird

I agree. There's a reason that tools like `prettier` are so popular in the webdev community - it lets devs pick one formatting tool that's good enough and move on. ktlint provides that to the Kotlin community. Sure, some would like to override some of ktlint's rules, but they miss the point of the tool. Maybe part of the motivation to wrap ktlint and make it configurable is because ktlint refuses to lint indentation when code is indented with tabs like detekt? :P

> The maintainance is quite low.

Updating wrappers is easy. But: #1299 #1249 #1233 #1078 (plus other closed issues that took time to triage and investigate).

> Let ktlint handle formatting and styling. Let Detekt do static analysis.

IMHO I'd expect ktlint to have rules for the "do"s and "do not"s in the formatting section. Anything else ("should", "can", "consider" etc) would be fair game for detekt.

----
Could detekt-formatting move to its own repository?

**Comment by rumatoest** [comment]
> As I see it there are people actually using the ktlint integration in detekt.

Ktlint is not configurable unless you create your own plugin/module/whatever for it. And this is really unwise for them.

Detekt is already wraps ktlint and provide some verbose configuration over it. You just should check if everything work properly.

I do not need separate Detekt and Ktlint in my project if Detekt can do the same

**Comment by 3flex** [comment]
Between this and #1281 it sounds like it provides enough value to continue wrapping ktlint and the decision is to keep the wrapper. I'm closing this just to get the issue count down slightly, please comment and/or reopen if you think this warrants further discussion. Thanks!

**Comment by 3flex** [comment]
I'm reopening this purely to discuss [today's post on the Pinterest Engineering blog](https://medium.com/@Pinterest_Engineering/pinterest-ktlint-35391a1a162f) which states:

> In the medium-to-long term, we plan to follow Stanley’s proposed roadmap by implementing a way to globally disable rules (ktlint’s most-requested feature)

When that happens, one of the primary advantages of detekt wrapping ktlint goes away - would that be time to remove the wrapping, or will it stay for other reasons?

**Comment by vanniktech** [comment]
> or will it stay for other reasons?

No.

**Comment by marschwar** [comment]
I never really understood why there is a ktlint integration in the first place as both tools in my opinion try to solve completely different problems. I use both individually and am totally fine with it.

**Comment by arturbosch** [comment]
> I'm reopening this purely to discuss [today's post on the Pinterest Engineering blog](https://medium.com/@Pinterest_Engineering/pinterest-ktlint-35391a1a162f) which states:
> 
> > In the medium-to-long term, we plan to follow Stanley’s proposed roadmap by implementing a way to globally disable rules (ktlint’s most-requested feature)
> 
> When that happens, one of the primary advantages of detekt wrapping ktlint goes away - would that be time to remove the wrapping, or will it stay for other reasons?

Interesting, yep less maintenance is always good ^^

**Comment by schalkms** [comment]
> In the **medium-to-long term**, we plan to follow Stanley’s proposed roadmap by implementing a way to globally disable rules (ktlint’s most-requested feature)

I think **medium-to-long term** could mean a lot.
I'm not even sure whether ktlint users are aware that detekt already provides this most requested feature. (see https://github.com/pinterest/ktlint/issues/208)

I think that dropping detekt's own formatting rules was a wise choice in order to not reinvent the wheel.
I don't think we should remove the ktlint wrapper in the meantime.
Moreover, I'm not sure if we should remove it after ktlint provides a *native* configuration option.

**Comment by schalkms** [comment]
In addition to the Sonar integration we will also provide **exclusion and inclusion patterns** as an enhancement with RC15.

**Comment by 3flex** [comment]
Now 1.0 is released I think this debate is over for now. Maybe we can open again in 12 months ;)

**Comment by marschwar** [comment]
Reopening this once again, to get a sense of where we stand on the issue. I do not know if there are any new talking points one way or the other. Especially I don't know if the performance degradation has changed.

I am off the opinion that ktlint focuses on formatting while detekt is all about syntactical or structural code smells.

To me the best possible outcome world be the ktlint maintainers see this integration as beneficial for their project and pick up the maintenance for it - as there obviously seems to be a demand for it.

**Comment by 3flex** [comment]
Locking as any feedback on this should be posted on this discussion, as well as votes for or against removing it: https://github.com/detekt/detekt/discussions/5997

**Comment by BraisGabin** [comment]
Closing in favor of #5997.
