### ISSUE TITLE
Refactor: Type and symbol solving logic

### ISSUE THREAD

**Issue by schalkms** [detekt/detekt#1909]
Since we use type and symbol solving for some rules now, it would be good to have an API, which encapsulates this logic and thus removes the code duplication from the rule related code.

**Comment by 3flex** [comment]
I like this idea, but other than checking for non-empty `BindingContext` (and issuing a warning when empty so user knows rule won't work as advertised), I'm not sure there's anything that would be considered standard between rules/visitors that need type resolution. Do you have some other ideas around this?

**Comment by schalkms** [comment]
I've looked into it. I agree that the `if` check is the only code that could be refactored.
I don't know, whether issuing a warning is the right thing to do here. Where do you want to print this warning? Should detekt even swallow this issue?

**Comment by 3flex** [comment]
It's tricky now because only JVM projects run from Gradle get the classpath setup automatically. It's manual for Android projects (though I have a nearly working solution to generate the Gradle tasks) and on CLI. Some documentation needs to be written as well.

So I don't think throwing an error is suitable until those things are resolved.

It's still an "experimental" feature but as more rules are converted an added that rely on it, it can't be experimental much longer as you said.

**Comment by arturbosch** [comment]
We should introduce a new property `needsTypeResolution` on `Rule`. This way we can move the `BindingContext.isEmpty` to the `condition` check function.

**Comment by BraisGabin** [comment]
Can we close this? #3127 and other issues related with detetk 2.0 already handle this topic and they are more updated.
