### ISSUE TITLE
Align cli flags and defaults with other analysis tools

### ISSUE THREAD

**Issue by arturbosch** [detekt/detekt#2267]
## Expected Behavior
`--build-upon-default-config` should be `true` by default.
new flag `--all-rules` which activates all rules
remove `--fail-fast`
introduce new flag `--max-issues` to quickly manipulate the number of allowed issues without having a config file.

## Current Behavior
`--fail-fast` does three things: `--build-upon-default-config` + `maxIssues=0` + activates all rules

## Context
Align behavior wiht tools like PMD and ESLint

**Comment by BraisGabin** [comment]
Are we sure that `--fail-fast` always sets the `maxIssues` to `0`? The code doesn't do that:
https://github.com/detekt/detekt/blob/c1ebc037f9f3bb161f39157f2d71a964ee24527c/detekt-api/src/main/kotlin/io/gitlab/arturbosch/detekt/api/internal/FailFastConfig.kt#L15
and even the tests doesn't assert that:
https://github.com/detekt/detekt/blob/c1ebc037f9f3bb161f39157f2d71a964ee24527c/detekt-core/src/test/kotlin/io/gitlab/arturbosch/detekt/core/WorkaroundConfigurationKtSpec.kt#L68

I vote to remove the support to `--fail-fast`. It's buggy and no one complains about it. And it really work in really special situations because nearly always we end using the defaul configuration as the base configuration and because of this line:
https://github.com/detekt/detekt/blob/c1ebc037f9f3bb161f39157f2d71a964ee24527c/detekt-api/src/main/kotlin/io/gitlab/arturbosch/detekt/api/internal/FailFastConfig.kt#L14

We just run the rules that are active by default.

**Comment by arturbosch** [comment]
Your right, it set the default `maxIssues = 0` when the old threshold was 10, configs can overwrite it.
Now it's just `--build-upon-default-config + activates all rules`.

@BraisGabin have you started with this issue? If not, I want to look at this next.

**Comment by BraisGabin** [comment]
You can do it. All my work is the wip pr that I want to close. I'll try to focus on the dsl.

**Comment by arturbosch** [comment]
> You can do it. All my work is the wip pr that I want to close. I'll try to focus on the dsl.

Ah, rediscovered your PR. A good starting point.

**Comment by chao2zhang** [comment]
The remaining tasks are:
- Enable `--build-upon-default-config` by default
- Remove `--fail-fast`

**Comment by BraisGabin** [comment]
Probably this two should be done for 2.0, right?

**Comment by arturbosch** [comment]
> The remaining tasks are:
> 
> * Enable `--build-upon-default-config` by default
> * Remove `--fail-fast`

added it to https://github.com/detekt/detekt/issues/2692#issuecomment-767711612
