### ISSUE TITLE
Get detekt a logo

### ISSUE THREAD

**Issue by cortinico** [detekt/detekt#2717]
Detekt is close to reach 3K stars (🎉 we should celebrate) and I have the feeling is really time to find a proper logo for this project.

I already found a couple of scenarios where having a logo would be helpful:
- Third party tools that integrate Detekt inspections (e.g. [Codacy](https://app.codacy.com/manual/v.buberenko/chucker/file/44709071631/issues/source?bid=16089375&fileBranchId=16089375#l11)). 
- Github Actions or Apps that integrate detekt (e.g. https://github.com/Mkohm/detekt-hint)
- General material coming from the community (e.g. detekt is one of the few tools without a logo in this [ecosystem spreadsheet](https://github.com/igorwojda/android-ecosystem-cheat-sheet))

It think it would be great if this comes as a community contribution. Maybe someone with graphics skills can draft some proposals.

**Comment by schalkms** [comment]
Thanks for bringing this to attention again! AFAIK @arturbosch is working on a logo for detekt.

**Comment by arturbosch** [comment]
Thanks for the issue!
It's on hold right now. However you will know it first in this issue :)

**Comment by cortinico** [comment]
Do we have any updates on this? I could come up with a draft if you wish @arturbosch

**Comment by arturbosch** [comment]
> Do we have any updates on this? I could come up with a draft if you wish @arturbosch

No, sorry for that. Yes please go on with the draft nico

**Comment by cortinico** [comment]
I've asked a friend of mine to come up with an idea. In the meanwhile, if someone from the opensource community wants to drop their ideas in this thread, feel free to do it 🙏

**Comment by cortinico** [comment]
Ok so we have some updates.

I originally drafted this:
<img width="50%" alt="Screenshot 2021-02-19 at 16 43 32" src="https://user-images.githubusercontent.com/3001957/108531988-9d729780-72d7-11eb-98dd-32d22fa827c8.png">

I sent it over to a designer friend of mine (Thanks Paya 🙏) and she came up with several variations:

<img width="1247" alt="Screenshot 2021-02-19 at 16 43 32" src="https://user-images.githubusercontent.com/3001957/108532127-cdba3600-72d7-11eb-853e-a986c888d38f.png">

What's our take? We could also restrict the selection to some of them and use GH reactions to run a poll over them :)

**Comment by chao2zhang** [comment]
I came to https://kotlinlang.org/docs/guidelines.html#unpermitted-uses for usage of Kotlin logo. In this regard, I would vote for the 3 logos in the bottom right.

I have checked mockk, koin, ktlint. None of them are reusing Kotlin logo. On the other hand, the kotlin official libraries like anko include the original Kotlin language logo.

Looking forward to a vote!

**Comment by schalkms** [comment]
Thanks for driving this idea forward! The design looks great. 🙂
 I would vote for the second to last logo with the orange background.

> I came to https://kotlinlang.org/docs/guidelines.html#unpermitted-uses for usage of Kotlin logo. In this regard, I would vote for the 3 logos in the bottom right.

I agree.

**Comment by BraisGabin** [comment]
I really like the orange as the main color of the icon (as the bottom one). 

I Wan to play the devil's advocate here: "So our logo will be "just a magnifier". Just as any search icon in any app/web."

To be clear, I really like idea of a magnifier as our logo. But if we don't use the kotlin logo (because we can't) we maybe need to do something "special" to that magnifier so it's not "any magnifier" but "the detekt's magnifier". What do you think?

**Comment by arturbosch** [comment]
> Ok so we have some updates.
> 
> I originally drafted this:
> <img alt="Screenshot 2021-02-19 at 16 43 32" width="50%" src="https://user-images.githubusercontent.com/3001957/108531988-9d729780-72d7-11eb-98dd-32d22fa827c8.png">
> 
> I sent it over to a designer friend of mine (Thanks Paya ) and she came up with several variations:
> 
> <img alt="Screenshot 2021-02-19 at 16 43 32" width="1247" src="https://user-images.githubusercontent.com/3001957/108532127-cdba3600-72d7-11eb-853e-a986c888d38f.png">
> 
> What's our take? We could also restrict the selection to some of them and use GH reactions to run a poll over them :)

Love the draft and the designs!

yeah, kotlintest had to change their name (kotest) and logo due to the kotlin logo restrictions.

So I would vote for first (white background) of the three last ones.

My gf came up with the idea to cut some lines from the K:

![detekt-logo-edited-K](https://user-images.githubusercontent.com/20924106/108603782-3d005a80-73aa-11eb-8198-0f2950ae0eea.png)

detekt finds "patterns" with a "magnifier" but the user still recognize the K from Kotlin.

**Comment by cortinico** [comment]
> To be clear, I really like idea of a magnifier as our logo. But if we don't use the kotlin logo (because we can't) we maybe need to do something "special" to that magnifier so it's not "any magnifier" but "the detekt's magnifier". What do you think?

+1 for the idea suggested by @arturbosch of having the K pattern below the magnifier.

We could even have it as a dotted line in some way.

As for the colors, I'll be in for the orange as it's a strong accent color. It would play well if we plan to rebrand the website a bit.

**Comment by chao2zhang** [comment]
Good to know that there are more people interested in rebranding our website 🎉

**Comment by schalkms** [comment]
> Good to know that there are more people interested in rebranding our website 🎉

+1
I'm also interested in a rebranding. 🙂

**Comment by JavierSegoviaCordoba** [comment]
Something so but improving the D
- Another font
- Improve my bordering
- Improve the oblique lines

![image](https://user-images.githubusercontent.com/7463564/110204665-8ce42480-7e74-11eb-8c57-c5e4db0991fc.png)


### Ideas
![image](https://user-images.githubusercontent.com/7463564/110204779-34f9ed80-7e75-11eb-9de6-27d269a50976.png)
- I think both logos are fine, one without the detekt word for circle avatar (GitHub organization for example) and another one for a badge.
- Probably the glass should be there too as a standalone icon so we can create a shields.io badge to show in the readme of the libraries that detekt is used and which version has, for example.

### Summary:

1. General logo which fits square/rounded avatars
2. Logo with the detekt word for heading docs, etc
3. Add the Glass as a standalone icon to the branding asset too to allow creating badges.

**Comment by cortinico** [comment]
I got some new designs from Paya <3

![unnamed](https://user-images.githubusercontent.com/3001957/110619066-a8fb0500-8197-11eb-83dc-9b232f8645ba.png)

**Comment by JavierSegoviaCordoba** [comment]
The first one and the two last for me :)

**Comment by chao2zhang** [comment]
+1 for the first one and the two on the bottom row.

**Comment by schalkms** [comment]
>+1 for the first one and the two on the bottom row

same here

**Comment by arturbosch** [comment]
The second one is very stylish.
I also like the last two with lowercase `detekt` most.
I vote for the last because of the color :)

**Comment by cortinico** [comment]
How do we all feel about having `!!` in the logo? Is that relevant for Kotlin? I feel like that's one of the primary source of codesmell for Kotlin, but I'm not sure everyone gets the reference 🧐

**Comment by chao2zhang** [comment]
Detekt targets finding those code smells. I don't think the logos at the bottom row are confusing or ambiguous.

**Comment by G00fY2** [comment]
To be honst I didn't get the reference at first glance but it makes perfect sense! But even without having the **!! Operator** in mind I found the exclamation marks very suitable, since you can also see them as multiple warnings that detekt informs you about.

I also like the logo at the bottom right the most. It also matches best with JetBrains current Kotlin design appearance which is mostly purple and not orange. As a reference the latest Kotlin intro design: https://youtu.be/ZFKxAYvQ7wQ?t=298

**Comment by BraisGabin** [comment]
I like the last one too.

**Comment by chao2zhang** [comment]
I like to change my vote to last one (in dark mode, the text should be white)

**Comment by 3flex** [comment]
I also like the last one! I think that's unanimous? My only thought about the colours, though I also prefer it to the orange, is that the pink component (if we used it in any website themes etc) is maybe too similar to ktlint which uses pink heavily. Probably doesn't matter much though since the projects aren't in competition (I hope!)

What do we need to do to get this over the line? Explicit permission from the artist, vector assets etc. Then I don't know if there's the appetite to protect the trademark or not... Given this a purely volunteer-driven project it's likely not worth the hassle but I just thought I'd raise it.

**Comment by payathedo** [comment]
Hi guys, this Paya. I am not a contributor yet therefore i can't create a branch to upload the assets. Here are the 2 color variations assets (with horizontal, vertical logos & icons).
[logos.zip](https://github.com/detekt/detekt/files/6370105/logos.zip)

**Comment by BraisGabin** [comment]
@payathedo Thank you so much!!!

Next steps? I see:
- Add svg the files to the repo. Or is there other better place where we could store them?
- Update the Readme to add the logo
- Update the doc/index to add the logo
- Update the logo of detekt organization -> https://github.com/detekt/

I think that with that we could close this issue.

**Comment by JavierSegoviaCordoba** [comment]
Favicon too

**Comment by G00fY2** [comment]
Another point on the checklist should be: [Customizing your repository's social media preview](https://docs.github.com/en/github/administering-a-repository/customizing-your-repositorys-social-media-preview)

You probably also need different aspect ratios (e.g. a square version).
