### ISSUE TITLE
Detekt (Gradle Task) should implement `Reporting`

### ISSUE THREAD

**Issue by runningcode** [detekt/detekt#2721]
Detekt (Gradle Task) should implement the Reporting interfaces to make it easier to configure reporting tasks in a general way.
This makes it easier to configure reporting across all tasks in the project in a single way and gather the reports and aggregate them.

See the checkstyle task for an example:
https://github.com/gradle/gradle/blob/3f79806c3599f54ca006412c23a0fe1d20698e98/subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/Checkstyle.java#L58

**Comment by 3flex** [comment]
I looked into this some time back, and it doesn't seem feasible - see https://github.com/gradle/gradle/issues/7063 for some of the background. The Checkstyle tasks can implement `Reporting` interface easily by taking advantage of implementations in Gradle's internal API, but since detekt is a third party plugin it can't do the same.

Note also the first comment on that issue, written by one of the Gradle team, which says
> The `Reporting` interface isn't really intended to be implemented outside of the Gradle core plugins.

If you have any suggestions on how to implement that would be welcome, but otherwise I recommend closing as wontfix.

**Comment by runningcode** [comment]
This makes sense.

**Comment by arturbosch** [comment]
Thanks for the additional info @3flex !
