### ISSUE TITLE
Add an annotion exclusion to ProtectedMemberInFinalClass

### ISSUE THREAD

**Issue by tomwijgers** [detekt/detekt#2747]
Expected Behavior of the rule

I would like to add an exclusion to this rule if the member has a particular annotation, so the first member would be caught, but the second wouldn't.

```
class TestClass() {
    protected var thisShouldBeCaught: Int = 0
    @Inject
    protected lateinit var thisShouldNotBeCaught: InjectedClass
}
```
## Context
Dagger doesn't support injecting into private fields, so protected is the best scope, even though it is inside a final class

**Comment by cortinico** [comment]
I can take care of this 👍

**Comment by schalkms** [comment]
Thanks for raising this proposal! It’s always good to know which dependencies users have in their projects.

In this case I’m against adding this to detekt. You might ask why. Maybe 0,002 % of the user base reference dagger. Just because 1 framework has some specialities, we shouldn’t add the complexity to detekt. Remember that this has to be maintained as well. Usually the suppress annotation is the way to go here. A custom domain-specific rule could also work in your case.

Detekt tries to include rules which are relevant for the majority of the user base. It can’t handle the peculiarities of every framework in the Kotlin/Java world in the standard ruleset.

**Comment by cortinico** [comment]
I don't have a strong opinion on this, but just as a FYI: we already added similar configurations in the past that are specifically designed around a library:

https://github.com/detekt/detekt/blob/56fe14f47e22f08f740b6d31ae03daad5dfcd262/detekt-cli/src/main/resources/default-detekt-config.yml#L354-L360

https://github.com/detekt/detekt/blob/56fe14f47e22f08f740b6d31ae03daad5dfcd262/detekt-cli/src/main/resources/default-detekt-config.yml#L591-L593

https://github.com/detekt/detekt/blob/56fe14f47e22f08f740b6d31ae03daad5dfcd262/detekt-cli/src/main/resources/default-detekt-config.yml#L513-L517

So to me this felt like a similar scenario

**Comment by BraisGabin** [comment]
After read this issue and #2231 I added a new comment mixing different proposals. Could you read it and see if it would help?

**Comment by schalkms** [comment]
Discussion continues in #2231 for an easier overview.
