### ISSUE TITLE
Upload detekt-formatting plugin to Github releases next to precompiled cli binary

### ISSUE THREAD

**Issue by Mygod** [detekt/detekt#2927]

**Comment by arturbosch** [comment]
There is the `--plugins` flag to add extensions:

```bash
detekt --plugins detekt-formatting/build/libs/detekt-formatting-1.11.0-RC1.jar  --input detekt-core/
```

**Comment by Mygod** [comment]
Where can I find this jar?

**Comment by cortinico** [comment]
You can download it from bintray: https://bintray.com/arturbosch/code-analysis/detekt/1.11.0-RC1

Specifically the mentioned jar is this one: 
https://bintray.com/arturbosch/code-analysis/download_file?file_path=io%2Fgitlab%2Farturbosch%2Fdetekt%2Fdetekt-formatting%2F1.11.0-RC1%2Fdetekt-formatting-1.11.0-RC1.jar

Please close the issue if your issue is solved 👍

**Comment by Mygod** [comment]
Thanks though I expect it should be released alongside the main cli.

**Comment by Mygod** [comment]
Hmm I am not able to find 1.14 artifacts...

**Comment by arturbosch** [comment]
Hey @Mygod,
we moved to maven central (https://mvnrepository.com/artifact/io.gitlab.arturbosch.detekt/detekt-formatting/1.15.0-RC1) due to unstable releases when uploading to many files to Bintray.
