### ISSUE TITLE
Gradle Plugin: Different behaviour detekt and detektMain

### ISSUE THREAD

**Issue by wulfcolin** [detekt/detekt#2936]
The **potential bugs** **UnsafeCast** and **UnsafeCallOnNullableType** are not detected with the gradle task **detekt** but they are detected using **detektMain**. Other rule violations like **EqualsAlwaysReturnsTrueOrFalse** are detected with both tasks

Steps to reproduce: 
- Create a Kotlin 1.3.72 project using Gradle 6.5.1
- Add detekt 1.11.0-RC1 (also had the issue with 1.7.4)
- Generate the default config using _detektGenerateConfig_ and set _UnsafeCast_ to active
- Create a .kt File containing the non-compliant code samples for those rules
- Execute the tasks _detekt_ and _detektMain_

If necessary I provide a minimal example tomorrow

**Comment by BraisGabin** [comment]
That is working as intended. `detektMain` enables type solving and it's needed for those rules that you talk.

Anyway I'm going to keep this issue open because here we have a problem in the expectations.

Should we support the no type solving option for 2.0? It's really misleading to have a rule enabled but no working.

**Comment by wulfcolin** [comment]
I see! Thanks. If you think more about it, it makes sense. But I think it would beneficial to highlight those rules that do not work without type solving (e.g. a small note next to them).

**Comment by cortinico** [comment]
> Should we support the no type solving option for 2.0? It's really misleading to have a rule enabled but no working.

Agree on it being really confusing for the user. We already received several similar issues like this one. Ideally we should have the type solving option as an opt-out for 2.0 (on by default and you can disable it say for performance reasons).

**Comment by schalkms** [comment]
I’m think type and symbol should be mandatory.
Thus, complexity for some rules is reduced and we don’t have to deal with issues like this. It’s rather confusing from a user point of view.

**Comment by BraisGabin** [comment]
> I’m think type and symbol should be mandatory.
+1. I think the same. It introduces complexity in both side. The rules are more complex and the user is more confused. If you remove type solving you don't know which rules work, which don't and which others works but only in some cases.

**Comment by BraisGabin** [comment]
After reading #2937 I had another idea:

The rules that work with and without type solving should be moved for only work with type solving for sure because they are the most misleading ones. But we can have a "virtual rule set" with the ones that doesn't need it at all. I explained my idea about virtual rule sets at https://github.com/detekt/detekt/issues/2680#issuecomment-668825206. This way you can run a "fast check" over some of our rules. For sure this fast check would be an opt-in thing.

This is an idea but I'm not sure how much value this could bring and if it's worth the complexity.

**Comment by schalkms** [comment]
Closed since the original issue is clarified.
The discussion regarding the type and symbol configuration option is going in the linked issues.
