### ISSUE TITLE
Should the Baseline task generate a baseline file when no issues are recorded?

### ISSUE THREAD

**Issue by realdadfish** [detekt/detekt#3024]
Personally I think it should not, because the mere existance of a baseline file - even if empty - suggests that it is ok for developers to add issues to it, either manually or by calling the respective baseline task.

What do you think?

**Comment by arturbosch** [comment]
Hm, even empty baseline files introduce VCS noise, so I'm okay to change this behavior.
An appropriate message should be printed instead ^^.

**Comment by BraisGabin** [comment]
I disagree here. Usually the configuration that we have for detekt is like this
```groovy
subprojects {
  detekt {
    baseline = // ...
  } 
}
``` 
So you are adding the baseline feature to all the modules.

But what you are talking about is that you don't like to enable the baseline feature for all your modules. And I agree that doing that let the users to use the baseline more.

But I think that the way to resolve this is to remove the `baseline` from `subprojects` and only add it in the modules that you **really** want to use the baseline. This the baseline is an opt-in feature that you need to configure per module. And this is a better way to discorage its use.

**Comment by realdadfish** [comment]
The thing is - most people configure Detekt via global scripts, like a `subprojects {}` block in the root `build.gradle(.kts)` and might think of this configuration as "if the module-specific file is there, use it, if not, ignore it". At least this is how I used to think about and use it.

**Comment by BraisGabin** [comment]
I agree, that's how the most people configure detekt. And that's probably for a lack of documentation. I mean, we really don't say how to configure detekt in a multimodule so the users just copy&paste from other open source project or detekt itself. And we have that configuration. The first time that I configured detekt I just copy&paste the one that detekt itself was using.

> Personally I think it should not, because the mere existance of a baseline file - even if empty - suggests that it is ok for developers to add issues to it, either manually or by calling the respective baseline task.

If you want to discorge the use of baseline you should not enable it by default. It should be an opt-in. And, while I'm writing this, I'm doing this change in one of my projects.

**Comment by arturbosch** [comment]
I must admit I'm always using one top level baseline file with a custom `createProjectBaseline` task.
So there is one baseline file or none for the whole project.

Imo Gradle is all about convenience so I I'm okay in skipping the baseline file (when using `subprojects { ... }`) and printing a warning on the Gradle plugin side.

I mark this issue as needs feedback and discussion.

**Comment by realdadfish** [comment]
> I must admit I'm always using one top level baseline file with a custom `createProjectBaseline` task.
> So there is one baseline file or none for the whole project.

How is this working with type resolution, do you configure that single task to include all module classpaths and sources?

**Comment by ashalmawia** [comment]
@BraisGabin 
>But I think that the way to resolve this is to remove the baseline from subprojects and only add it in the modules that you really want to use the baseline. This the baseline is an opt-in feature that you need to configure per module.

I have exactly the set up you describe, because we do find it beneficial for modules to opt-out, and `./gradlew detektBaseline` fails because of those modules which don't have a baseline saying baseline property is not defined.

>* What went wrong:
A problem was found with the configuration of task ':appServices:bsbhelper:detektBaseline' (type 'DetektCreateBaselineTask').
\> No value has been specified for property 'baseline'.

Could you please describe how the solution you suggest is expected to work in practice? Do I have to list specifically which modules to run `detektBaseline` for, instead of running it once for the whole project?.. This would not be possible in our case as we have 100+ modules.

I had to end up with manually disabling `detektBaseline` for the modules not specifying baseline in `afterEvaluate`. Since you mention the problem, is there a more obvious solution that I miss?

**Comment by BraisGabin** [comment]
Good point! I must admit that I didn't implement my solution yet but what you mention have sense. When we run detektBaseline we expect to have a baseline path defined. And if it's not the task fail... Maybe that's what we should fix. But I don't know which direction should we follow. I'd like to know the opinion of more users/maintainers

**Comment by realdadfish** [comment]
It used to fail on that, which I worked around in my own projects with a conditional configuration of a specific baseline file for projects that had one. Since the merge of the Android support this however is no longer needed (at least for the type-resolution-enabled tasks), as source-set and variant-aware baseline files might exist and so I check in the plugin itself if - and if yes - what baseline file exists before I set it on the respective baseline task.

**Comment by ashalmawia** [comment]
Skipping `detektBaseline` for modules which don't specify the `baseline` property would provide an easy and flexible way for modules to opt-out from baselines. For projects like ours, where baselines are used because of tons of legacy code with a single purpose to gradually bring baselines down and remove one day, this would be a perfect solution.

**Comment by FatihYalmanbas** [comment]
I have using detekt since early releases, I have been using it in projects with up to 40 kotlin modules. Normally i'd be on the "Let's define project related build configurations in project level build.gradle file and reuse them as buildSrc or individual build scripts" side, but when you have more than 10-15 modules and all of them needs to be configured, I rather have a plugin that creates less noise and configure it through root project build script.

**Comment by schalkms** [comment]
Are there any efforts to drive this forward?
Are there any definitive decisions?
Otherwise, we should close this, I think.
