### ISSUE TITLE
Thresholds for Kotlin Compiler warnings

### ISSUE THREAD

**Issue by dsvensson** [detekt/detekt#3095]
Kotlin compiler detects unused variables, nullable calls on non-nullables etc, but it doesn't have the ability to mark specific warnings as errors, it's all or nothing. It would be great if detekt could add ability to configure thresholds for built-in warnings.

The Kotlin team doesn't seem too keen on fixing it on their end, this issue has been open for 3 years:
https://youtrack.jetbrains.com/issue/KT-18783

**Comment by cortinico** [comment]
> It would be great if detekt could add ability to configure thresholds for built-in warnings

That's probably outside of the scope of Detekt. What detekt can do is wrap compiler findings into rules and you can use those rules instead of the compiler warnings. An example is the `UnnecessarySafeCall` rule:

https://github.com/detekt/detekt/blob/87d2fc29ee4824b97abc40c91ff25ffe825f670a/detekt-rules-errorprone/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/bugs/UnnecessarySafeCall.kt#L51

If you have suggestions for built-in warning that are worth a detekt rule, feel free to suggest.

**Comment by dsvensson** [comment]
Based on searching for bindingContext.diagnostics.forElement in the repo there seems to be missing shadowed stuff, unused variables. It would also be interesting to treat _"... is deprecated. Use ..."_ specially so it's possible to filter on internal vs external dependencies. Like erroring on use of deprecated external deps, but allow use of internal deprecated functions.

**Comment by dsvensson** [comment]
As for UnnecessarySafeCall, not sure how to trigger it. The compiler outputs `Unnecessary non-null assertion (!!) on a non-null receiver of type UUID` but setting that check to active does not seem to catch that one. Does it cover some other case?

**Comment by cortinico** [comment]
> Based on searching for bindingContext.diagnostics.forElement in the repo there seems to be missing shadowed stuff, unused variables. It would also be interesting to treat _"... is deprecated. Use ..."_ specially so it's possible to filter on internal vs external dependencies. Like erroring on use of deprecated external deps, but allow use of internal deprecated functions.

Please open a separate issue for every report. We might already have a rule that covers that scenario (and doesn't rely on compiler warnings).

> As for UnnecessarySafeCall, not sure how to trigger it. 

That rules works only with type resolution enabled

> The compiler outputs `Unnecessary non-null assertion (!!) on a non-null receiver of type UUID` but setting that check to active does not seem to catch that one. 

That's captured by the https://github.com/detekt/detekt/blob/master/detekt-rules-errorprone/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/bugs/UnnecessaryNotNullOperator.kt rule.

> Ah is that perhaps `SomeNonNullable?.foo`

`UnnecessarySafeCall` captures exactly that.

**Comment by schalkms** [comment]
I agree with Nico here.
This is out of scope for detekt's main repo and the provided functionality.

However, this doesn't mean that it's not possible.
One could, for instance, use detekt's rich extension functionality to implement this domain specific feature.
Please take a look at our how-to page, which summarizes detekt's extension functionality.

https://detekt.github.io/detekt/extensions.html

**Comment by BraisGabin** [comment]
I think that this things should no be out of the scope of detekt. I mean, we are not going to read the compiler output but we should handle things like the use of deprecation classes/functions/properties and other things that the compiler checks and we don't.

I know that there was a issue talking about this but I can't find it. The points there were that we should not replicate the rules that the compiler checks already.

But I think that we should rethink that. Some reaons:
- The warnings are not spotted by CI so they keep growing out of control.
- You can user `allWarningsAsErrors` but:
  - There's not baseline
  - There's not way to ignore some rule
  - You can't enable it just in CI and use "gradle cache". Work in local with `allWarningsAsErrors` is impossible, it doesn't let you "hack around" to find problems (an example is to remove all the code from a function to see what happen. You can't do it because you will get a compilation error "parameter unused"). And, if you enable it just in CI you can't get the goodies of gradle cache because the input of the task is different so it always miss. For me this is the big problem that can't be workarounded.

**Comment by dsvensson** [comment]
I'll just wrap gradle in a script and grep the output to fail the build.

**Comment by BraisGabin** [comment]
We can keep this open. Even if there are some workarounds, detekt should handle this.

**Comment by dsvensson** [comment]
This is still a problem.

**Comment by cortinico** [comment]
What's actionable here?

**Comment by dsvensson** [comment]
@cortinico I guess collaborating with the Kotlin compiler team?

**Comment by BraisGabin** [comment]
After reading this https://publicobject.com/2022/02/02/compiler-warnings-are-good-actually/ I thought about this issue again.

I think that give the option to "baseline" the warnings would be great. Yo don't want to add new warnings in your code but if you want to update kotlin or a library you should be able to do that and fix the warnings later (later != never).

But probably this should be done in a plugin and not in the main project so, to me, we can close it.

**Comment by dsvensson** [comment]
@BraisGabin Adding a deprecation annotation before removing all the use is not uncommon.

**Comment by BraisGabin** [comment]
I did a small research on this. And I found a way to implement this and other similar rule:

```kotlin
bindingContext.diagnostics
    .filter { it.severity == org.jetbrains.kotlin.diagnostics.Severity.WARNING }
    .forEach {
        report(
            CodeSmell(
                issue,
                Entity.from(it.psiElement),
                "Kotlin compiler warning message"
            )
        )
    }
```

and

```kotlin
bindingContext.diagnostics
    .filter { it.severity == org.jetbrains.kotlin.diagnostics.Severity.INFO }
    .forEach {
        report(
            CodeSmell(
                issue,
                Entity.from(it.psiElement),
                "Kotlin compiler info message"
            )
        )
    }
```

As other maintainer said and now I agree with (my bad), this is out of scope for detekt, so I'm closing this issue.

But that doesn't mean that those rules shouldn't be implemented. I'm going to create that third-party rule set so anyone can use it. (I'll add a link in this issue as soon as it is implemented)
