### ISSUE TITLE
Rule: Possible Semicolon Inference Issues

### ISSUE THREAD

**Issue by emartynov** [detekt/detekt#312]
How about to add a new rule for next the case?

```
//First Part
val var1 = 1 + 2 + 3 + 4
println(var1)

//Second Part
val var2 = 1 + 2
              + 3 + 4
println(var2)

//Result
//10
//3
```

**Comment by arturbosch** [comment]
I do not exactly understand what you mean. Can you elaborate on that?

**Comment by Mauin** [comment]
My guess: It's sometime possible due to non-semicolon linebreaks that some statements are just not assigned as you would expect. In the second part of the example there is the `+ 3 + 4` hanging of on a new line which will not be assigned to `var2`. 
The Rule would find such cases and report them. Although I'm not sure how to properly detect these things.

**Comment by schalkms** [comment]
Thank you for the idea. I like the rule.

**Comment by emartynov** [comment]
@Mauin explained what I had in mind.

I got the question on android slack about this issue and first (since java still sits in my mind) I didn't understand what is going from. Later I made a test to reproduce it and formatted it and then I realised problem of doing something on the new line.

**Comment by arturbosch** [comment]
Ok now I understand. 

```
val var1 = "" + ""
		+ ""
val var2 = listOf(1) + listOf(3)
		+ listOf(5)
```

Above case do not work, so this issue only works for numbers?

**Comment by Mauin** [comment]
We could rename this Issue to "Rule: Possible Semicolon Inference Issues" .

**Comment by schalkms** [comment]
I think this should also be reported to the Kotlin compiler team.
For now, we can of course implement a rule for this case.
