### ISSUE TITLE
Incorrect work of formatting rules with same parameters name

### ISSUE THREAD

**Issue by rwqwr** [detekt/detekt#3133]
Is it possible to use ParameterListWrapping.indentSize and Indentation.indentSize in same time?
Current behavior is overwrite values, for instance, when Indentation.indentSize = 4 and ParameterListWrapping.indentSize = 8 then Indention overwrites and checks as indentSize = 8

**Comment by CoderCoco** [comment]
I too have experienced this issue, I was banging my head against the wall trying to figure out why my `Indentation.indentSize = 2` was not applied. Turns out that I had used the default for `ParameterListWrapping.indentSize` which I believe was 4. Changed `ParameterListWrapping.indentSize` to be 2 as a workaround for now.

**Comment by cortinico** [comment]
> ParameterListWrapping.indentSize and Indentation.indentSize

Both `ParameterListWrapping` and `Indentation` are wrapping KtLint rules.
Can I ask you to try to replicate the issue on KtLint stand-alone and eventually open an issue on their issue tracker?

**Comment by schalkms** [comment]
Closed due to the issue in ktlint's repo.
