### ISSUE TITLE
Documentation on KDoc attributes.

### ISSUE THREAD

**Issue by Whathecode** [detekt/detekt#3244]
I don't know in which release, but at some point in the past after upgrading my custom rules were no longer `active` by default. I only just noticed now they no longer run.

I found the following in the [extending detekt documentation](https://detekt.github.io/detekt/extensions.html#pitfalls):

> By default all rules not marked with `@active` in their KDoc are disabled. That means your custom rules are also disabled if you have not explicitly enabled them in the detekt yaml configuration file.

However, even when adding `@active` in the Rule's documentation I still need to set the specific rules to `active` in `detekt.yml` for them to be executed. I noticed some rules in the detekt codebase list `@active since v....`. I tried this as well, which seemingly also didn't work.

Is there documentation on how to use this correctly? What might I be doing wrong?

**Comment by cortinico** [comment]
> By default all rules not marked with `@active` in their KDoc are disabled. 

This is true for the rules coming with detekt

> That means your custom rules are also disabled if you have not explicitly enabled them in the detekt yaml configuration file.

I believe this statement is not correct, but I'd love @arturbosch to verify it.
The `@active` or `@active since v....` is used by `detekt-generator` to render the `default-detekt-config` file. If a rule in detekt does not specify the `@active` annotation, that rule will be disabled.

The ` since v....` part is just for documentation as we just check if the `@active` tag is present and we never read the value:

https://github.com/detekt/detekt/blob/1eb5fff2d265d5f93a6e3b6736f7fd9d9aeb0d00/detekt-generator/src/main/kotlin/io/gitlab/arturbosch/detekt/generator/collection/RuleVisitor.kt#L91

**Comment by BraisGabin** [comment]
I think that the correct one for custom rules are:

> That means your custom rules are also disabled if you have not explicitly enabled them in the detekt yaml configuration file.

At the end of the day `@active` is just an annotation in the KDoc. At runtime detekt doesn't check those. So, I think that, to enable your rule, you should do it by yaml or overriding the property `active` in the rule.

We need to rewrite that documentation part.

**Comment by schalkms** [comment]
Closed by bd45a05
