### ISSUE TITLE
Stop publishing detekt-cli-all.jar in maven central

### ISSUE THREAD

**Issue by BraisGabin** [detekt/detekt#3329]
Does it have sense to publish `detekt-cli-all.jar` in maven central? We publish it in github and that's the url that we recommend in our [documentation](https://detekt.github.io/detekt/cli.html#unix-with-the-stand-alone-executable).

I don't know if we should even publish detekt-cli at all in maven central. But I think that for now that's a huge change. We could think about this for 2.0.

**Comment by cortinico** [comment]
What's the benefit of removing it? I don't have a strong opinion but I'm leaning towards keeping it. All of our artifacts should live in Maven Central, `detekt-cli-all.jar` as well. Moreover external libraries/tool that wish to interact with Central can do it easier as that's the `detekt-cli` artifact with the `-all` classifier.

If maintaining it is too much hassle, we can definitely remove it.

**Comment by BraisGabin** [comment]
Maintain our is kind of trivial. I just open this because I found it when I was refactoring buildSrc. It feels a bit strange to have it the but I have no strong opinions here.

**Comment by chao2zhang** [comment]
For example, Homebrew relies on `detekt-cli-all.jar`: https://github.com/chenrui333/homebrew-core/blob/04e2d548e166b22eda424052bb316046c3a2437e/Formula/detekt.rb

**Comment by tyvsmith** [comment]
Can we revisit this and continue publishing the cli-all artifact? At Uber, We've noticed that the -cli artifact was no longer published recently. This has caused an issue in upgrading detekt, since our toolchain requires a pull through maven central via our artifactory mirror.

This is done for a few reasons. Security, scans on artifacts be mirrored and verification of signatures. Redundancy in the case of issues in other hosts. Immutability, in the case that an artifact is changed in Github. This is standard for some other artifacts that need CLI access, like Gogle Java Format and Ktfmt.

**Comment by chao2zhang** [comment]
Good catch. I think this issue was closed without any action. The missing `cli-all` artifact is probably a bug (I noticed that the cli-all.jar existed for [1.17.0-RC2](https://repo1.maven.org/maven2/io/gitlab/arturbosch/detekt/detekt-cli/1.17.0-RC2/), but became missing in [1.17.0-RC3](https://repo1.maven.org/maven2/io/gitlab/arturbosch/detekt/detekt-cli/1.17.0-RC3/).

**Comment by cortinico** [comment]
Yup that's definitely a regression. I believe it was introduced by https://github.com/detekt/detekt/pull/3759. Seems like we're not picking up the `cli-all` artifact with `maven-publish` anymore, yet `shadow` is configured correctly.

To reproduce:

```
$ gw :detekt-cli:shadowJar && ls  detekt-cli/build/libs
Type-safe dependency accessors is an incubating feature.
Type-safe project accessors is an incubating feature.

BUILD SUCCESSFUL in 1s
76 actionable tasks: 76 up-to-date
detekt-cli-1.18.0-RC2-all.jar
```

While instead:

```
gw :detekt-cli:publishToMavenLocal && ls -l ~/.m2/repository/io/gitlab/arturbosch/detekt/detekt-cli/1.18.0-RC2/
Type-safe dependency accessors is an incubating feature.
Type-safe project accessors is an incubating feature.

BUILD SUCCESSFUL in 1s
22 actionable tasks: 3 executed, 19 up-to-date
total 360
-rw-r--r--  1 cortinico   279 Jul 23 23:03 detekt-cli-1.18.0-RC2-javadoc.jar
-rw-r--r--  1 cortinico   853 Jul 23 23:03 detekt-cli-1.18.0-RC2-javadoc.jar.asc
-rw-r--r--  1 cortinico 14467 Jul 23 23:03 detekt-cli-1.18.0-RC2-sources.jar
-rw-r--r--  1 cortinico   853 Jul 23 23:03 detekt-cli-1.18.0-RC2-sources.jar.asc
-rw-r--r--  1 cortinico 71924 Jul 23 23:03 detekt-cli-1.18.0-RC2.jar
-rw-r--r--  1 cortinico   853 Jul 23 23:03 detekt-cli-1.18.0-RC2.jar.asc
-rw-r--r--  1 cortinico  4944 Jul 23 23:03 detekt-cli-1.18.0-RC2.module
-rw-r--r--  1 cortinico   853 Jul 23 23:03 detekt-cli-1.18.0-RC2.module.asc
-rw-r--r--  1 cortinico  2660 Jul 23 23:03 detekt-cli-1.18.0-RC2.pom
-rw-r--r--  1 cortinico   853 Jul 23 23:03 detekt-cli-1.18.0-RC2.pom.asc
```

**Comment by BraisGabin** [comment]
I created a new issue to track this regression and my findings: #3969
