### ISSUE TITLE
Start detekt with Type Resollution

### ISSUE THREAD

**Issue by AlinaRakhimova** [detekt/detekt#3426]
Hi! 
A want to start detekt with type resolution in my Android project. But there isn't command detekt<Variant> in gradle task list. What i need to do to start this command?

<img width="823" alt="Снимок экрана 2021-01-29 в 15 21 41" src="https://user-images.githubusercontent.com/39618952/106274702-b4c4e480-6245-11eb-815b-f1595b6a3df9.png">

**Comment by cortinico** [comment]
(@arturbosch can you convert this to a discussion, or grant members the right to do that? 👌 )

You will find `detektMain` and other tasks with Type Resolution enabled inside your `app` (or libraries) module. What you're looking at now is the tasks from the `root` project.

**Comment by AlinaRakhimova** [comment]
I also don't see this command inside the app module


<img width="404" alt="Снимок экрана 2021-01-29 в 16 10 14" src="https://user-images.githubusercontent.com/39618952/106278997-c9f14180-624c-11eb-87a2-cf8ce2a3893d.png">

**Comment by AlinaRakhimova** [comment]
There is a demo in my repository https://github.com/AlinaRakhimova/customDetekt

**Comment by cortinico** [comment]
> I also don't see this command inside the app module

That happens because you're applying the Detekt Gradle plugin only on your root project and not on the `app` module. You can check this template https://github.com/cortinico/kotlin-android-template/blob/88719a470dfc3585e7af326503c90a52346886df/build.gradle.kts#L21-L50 for an example on how to setup the Detekt task on all of your subprojects.

**Comment by arturbosch** [comment]
> (@arturbosch can you convert this to a discussion, or grant members the right to do that?  )
> 

Could you test again? Technically you are now able to delete the detekt repo :D

**Comment by cortinico** [comment]
> Could you test again? Technically you are now able to delete the detekt repo :D

Turns out the feature was disabled by Github (https://github.com/github/feedback/discussions/2952#discussioncomment-279785) due to a bug on their end. They're slowly re-enabling the feature. I've asked for our repo to be re-added.

So I believe I actually already had the power to do so also before 👌

**Comment by AlinaRakhimova** [comment]
I added Detekt Gradle plugin in my app module. And now I have detektMain. Thank you so much!

**Comment by BraisGabin** [comment]
So, we can close this now, right?
