### ISSUE TITLE
Specify somewhere that core.autocrlf = true is required on Windows for working on detekt itself

### ISSUE THREAD

**Issue by utybo** [detekt/detekt#3659]
## Expected Behavior

Cloning and running `gradle build` works on Windows

## Observed Behavior

[This test](https://github.com/detekt/detekt/blob/9f894f56b9d8d91cfae994c626ead0b4e0628a8a/detekt-parser/src/test/kotlin/io/github/detekt/parser/KtCompilerTest.kt#L22-L30) fails due to the assertion line 25 which expects the system's line ending, i.e. `\r\n` on Windows. However, in order to have `\r\n` line endings on clone, you need to set the `core.autocrlf` Git option to `true`, otherwise the test fails because the file uses `\n` line endings.

## Steps to Reproduce

* Set `core.autocrlf` to `false` or `input` on Windows
* Clone the detekt repository
* Run `gradle build`

## Context

This makes the onboarding developers (e.g. me) confusing, as a seemingly random test fails for what appears to be no reason. This degrades the developer experience.

A fix could be to tell Windows user to use the following command in the README and CONTRIBUTING files:

```
git config --global core.autocrlf true
```

## Your Environment

* Version of detekt used: Main branch
* Version of Gradle used (if applicable): Wrapper version from detekt (6.8.3)
* Gradle scan link (add `--scan` option when running the gradle task): N/A
* Operating System and version: Windows 10
* Link to your project (if it's a public repository): N/A

**Comment by BraisGabin** [comment]
I agree, we have an issue here but I'm not sure if that's the way to fix it. I think that the problem is the test. We can't suppose that the same file in windows will have other end of line. But I'm not sure how can we fix it without losing coverage...

**Comment by 3flex** [comment]
I use Windows but I have `core.autocrlf` set to true, so I never saw this problem. But `true` is sometimes problematic for other projects I work on so asking people to change a global setting isn't the right approach.

Instead we can have OS-specific tests and/or skip this one on Windows. I'm not worried about loss of coverage since the code coverage task in CI is run on Ubuntu which wouldn't be affected.

**Comment by BraisGabin** [comment]
Well, that test checks that on windows it uses one end of line and on Linux it uses other. Maybe we can copy this test and add to both of them a skip. One only runs on windows and the other runs on Unix. This way on ci we have all of them running because we run in the 3 different OS and the contributors doesn't find this issue.
