### ISSUE TITLE
'detektJvmMain' Gradle task prints errors when relying on commonMain code, but still works

### ISSUE THREAD

**Issue by utybo** [detekt/detekt#3664]
## Expected Behavior

The `detektJvmMain` Gradle task just checks for errors within `jvmMain` sources and possible `commonMain` sources that compile properly.

## Observed Behavior

It does that, but also [prints compilation errors](https://github.com/utybo/detekt-kotlin-mpp/runs/2295387257#step:5:12), as it looks like it does not properly add the dependency to `commonMain`  to Detekt's internal compilation logic. In the above example, the issue reported by Detekt is correct (empty function body) but the two compilation errors are not.

## Steps to Reproduce

* Use `commonMain` code within `jvmMain` sources
* Run `gradle detektJvmMain` or `./gradlew detektJvmMain`

## Context

This is quite annoying for Kotlin MPP as the `detektJvmMain` gets spammed with errors that are not real errors. A [repro repo (that also highlights other issues)](https://github.com/utybo/detekt-kotlin-mpp) is available. I encountered this while trying to set up Detekt for [one of my projects](https://github.com/utybo/Lixy).

A possible workaround is to manually configure the `detekt` task to give it the inputs we want (JVM + common).

Note that this does not happen with JS code. I have not tested this with native code.

## Your Environment

* Version of detekt used: 1.16.0
* Version of Gradle used (if applicable): 6.8.3
* Gradle scan link (add `--scan` option when running the gradle task): https://scans.gradle.com/s/ll4mgfnk5j6ss
* Operating System and version: Windows 10, 19043
* Link to your project (if it's a public repository): https://github.com/utybo/detekt-kotlin-mpp

**Comment by cortinico** [comment]
Thanks for the great issue report @utybo, it's really valuable. Also thanks for the reproducer, that's really handy 👌 (I will keep on using it for a couple of other fixes on the KMP side).

> It does that, but also [prints compilation errors](https://github.com/utybo/detekt-kotlin-mpp/runs/2295387257#step:5:12), as it looks like it does not properly add the dependency to `commonMain` to Detekt's internal compilation logic.

What you're reporting could easily be fixed by us by changing the line here 
https://github.com/detekt/detekt/blob/14d3b5cd5e5304a6926171743cc1affde68e1e74/detekt-gradle-plugin/src/main/kotlin/io/gitlab/arturbosch/detekt/internal/DetektMultiplatform.kt#L37

to `val inputSource = compilation.allKotlinSourceSets`.

The side effect of this will be that the issues in the `common` srcSet will be reported for all the Detekt KMP tasks. I remember when discussing during the implementation of this feature, we decided to go for just `.kotlinSourceSet` as we also have the `detektMetadataMain` task that will work for the common source set.

We could potentially re-evaluate this.

**Comment by 3flex** [comment]
> We could potentially re-evaluate this.

If the decision is to change the behaviour then we can work on the PR, if it's to keep current behaviour this should be closed.

FWIW I think a nice middle ground is for the detekt task to report on all source sets that are involved in a given compilation by default, but to allow filtering of which source sets are analysed if desired.

**Comment by cortinico** [comment]
> If the decision is to change the behaviour

Yes we should change the behavior but we should potentially try to distinguish between:
* The sources that are needed for the sake of the compilation (`detektJvmMain` + `commonMain`)
* The input files where we want the inspector to run (`detektJvmMain` files only)

Currently this logic is not supported and should be added in the plugin.

**Comment by mecoFarid** [comment]
@cortinico Is there any workaround other than setting root of project as detekt's source ?

**Comment by cortinico** [comment]
> @cortinico Is there any workaround other than setting root of project as detekt's source ?

Nope sadly not. We hope to stabilize the `detekt-compiler-plugin` to handle those scenarios as well

**Comment by 3flex** [comment]
Closing. Changes since this issue was opened seem to have resolved this.

I checked out the project then did the following:
1. Updated KMP plugin to 2.0.20
2. Enabled detekt's debug mode
3. Updated to Gradle 8.10
4. Added detekt as an included build by adding this to settings.gradle:
```kotlin
pluginManagement {
    includeBuild("../detekt/detekt-gradle-plugin")
}
includeBuild("../detekt")
```
5. Ran `./gradlew detektMainJvm` (task name for this analysis task has changed).

Results here: https://scans.gradle.com/s/h7lirwhgcbxyi
