### ISSUE TITLE
Generating baseline with Detekt 1.18.0-RC1 + Kotlin 1.5.1 uses all remaining disk then fails

### ISSUE THREAD

**Issue by brentwatson** [detekt/detekt#3952]
## Expected Behavior

Generating baseline is currently using 100G+ of available disk space, until disk is full, then failing.
This happens with Detekt 1.8.0-RC1 and Kotlin 1.5.1.
It did not happen with Detekt 1.7.1 and Kotlin 1.4.32

## Observed Behavior

```zsh
❯ cd ~/code/my_android_project

❯ du -hs .
 11G	.

❯ ./gradlew detektBaselineMain detektBaselineTest
...
...
java.io.IOException: No space left on device
...
BUILD FAILED in 2h 47m 55s
16407 actionable tasks: 10060 executed, 5100 from cache, 1247 up-to-date
Publishing build scan...
The build scan publishing request was rejected as the data exceeded the maximum size.

❯ du -hs .
114G	.

❯ ./gradlew clean cleanBuildCache
...

❯ du -hs .
 11G	.
```

## Steps to Reproduce

This is a large android project (~1M lines of Kotlin, 300+ modules, and 20 product flavors), and we use detekt tasks that include type resolution.

## Context

We use the gradle plugin version of detekt.

Running `detektMain detektTest` tasks succeed.
Running `detektBaselineMain detektBaselineTest` task fail.

I've tried adding the following config to reduce the number of targets, but get the same issue (uses up all remaining disk space the fails):
```
      ignoredBuildTypes = ["release"]
      ignoredFlavors = [// all our flavors except for 1]
```

We have the following config:
- parallel = true
- allRules = true
- jvmTarget = "1.8"
- `classpath.setFrom(project.configurations.getByName("detekt"))` on both Detekt and DetektCreateBaselineTask tasks.

## Your Environment

* Version of detekt used: 1.8.0-RC1
* Version of Gradle used (if applicable): Gradle 7.0.2
* Gradle scan link (add `--scan` option when running the gradle task): Scan fails with "The build scan publishing request was rejected as the data exceeded the maximum size." error.
* Operating System and version: macOS Catalina (v10.15.7)
* Link to your project (if it's a public repository): N/A - not open source

**Comment by cortinico** [comment]
First, thanks for your report. This will help us ship a `1.18.0` that is hopefully bug-free.

>     * `classpath.setFrom(project.configurations.getByName("detekt"))` on both Detekt and DetektCreateBaselineTask tasks.

Why do you have this setup in your Gradle file?

> parallel = true

Just to troubleshoot, can you try to set this to false and let us know if it's still failing?

Also are you able to `cat` the baseline file and find out what's the content of the file (like if there are repeated lines or so)?

**Comment by brentwatson** [comment]
I did a `du | sort` to search for large files and there's not a single culprit. 

I did a `tree --du -h` diff before and after running the baseline commands and each module has about 500MB of data under `/build` vs only about ~5MB before I ran the command. In our project with ~300 modules, this adds up to ~150GB.

There are no individual files under `/build` that takes up all of this, but some of the larger ones are:

build/intermediates/incremental/debugAndroidTest-mergeJavaRes // 100MB
build/intermediates/incremental/debugAndroidTest-mergeNativeLibs // 100MB
build/intermediates/dex/debugAndroidTest // 80MB

**Comment by cortinico** [comment]
Thanks for the heads up.
I don't know what could be the exact reason for this. My gut feeling is that this could be the culprit: #3867. @damianw as you were the PR author, do you happen to have some relevant context?

@brentwatson would you be up to try a snapshot version?
Also I suppose that getting a reproducer would be hard right?

**Comment by cortinico** [comment]
> Why do you have this setup in your Gradle file?

Also can you follow up on this?

And this as well 🙏 

> Also are you able to cat the baseline file and find out what's the content of the file (like if there are repeated lines or so)?

**Comment by chao2zhang** [comment]
## Observation
This is reproducible using https://github.com/cortinico/kotlin-android-template.
- `./gradlew detektBaselineMain ; du -hs` using Detekt 1.17 - 29M - https://scans.gradle.com/s/vkyeqphs3sqf2/timeline
- `./gradlew detektBaselineMain ; du -hs` using Detekt 1.18-RC1 - 66M - https://scans.gradle.com/s/qbe3m4jiuebxe/timeline 
  When running `detektBaselineMain`, `assembleRelease` and `assembleDebug` would be run.

## Root cause
`registerIntermediatesJavacJarTask` has input path `intermediates/javac/${variant.name}/classes`, which means all tasks with the output targeting the path will be triggered. These tasks including assembling the app, and it worsened by assembling the app with 20 product flavors - @brentwatson if `./gradlew assemble` will run out of disk space, this may explain why `./gradlew detektBaselineMain detektBaselineTest`..

## Doubts
I am unclear why this is not a problem for `detektMain detektTest`.

## Potential suggestion
We could revert #3867, or protect the changes under a gradle property which by default is off.

**Comment by brentwatson** [comment]
Thanks for the info @chao2zhang! That PR looks promising for being the cause. As mentioned in PR description I did try running with  `ignoredBuildTypes` and `ignoredFlavors` config set to force only 1 build variation, but since the project still has 300 modules the disk space for each `/build` dir quickly adds up.

@cortinico , sorry for the delay, to answer your questions:

>>> * `classpath.setFrom(project.configurations.getByName("detekt"))` on both Detekt and DetektCreateBaselineTask tasks.
>>
> > Why do you have this setup in your Gradle file?
> 
> Also can you follow up on this?

This config was actually recommended to me by @arturbosch in #detekt channel in kotlinlang slack when we were trying to get tasks with type resolution running on our Android project. Message is [here](https://kotlinlang.slack.com/archives/C88E12QH4/p1579036522020200?thread_ts=1579029118.016400&cid=C88E12QH4).

> 
> And this as well 🙏
> 
> > Also are you able to cat the baseline file and find out what's the content of the file (like if there are repeated lines or so)?

The generated baseline file was previously only ~900 lines and only grew by ~100 lines before the tast fails - all that was added is entries for some new rules in v1.8.0.

**Comment by damianw** [comment]
Hmm, yes this does seem like the cause. Apologies - I only tested this on Gradle 6.8, and if my understanding is correct, I think this will only happen for Gradle 7.0+. From what I recall, there's some new requirements around task dependencies, where Gradle will infer additional task dependencies based on the input files.

With regards to @chao2zhang's comment:
> ## Doubts
> I am unclear why this is not a problem for `detektMain detektTest`.

This is probably because the specific task is only for Android projects (if you are referring to Detekt tasks for plain Java/Kotlin projects).

Reverting it seems sensible, as does protecting it behind a flag. There is probably a way to fix the task dependency issue, but I haven't invested enough time in learning the changes in Gradle 7 to be sure (assuming I'm correct that this problem is specific to Gradle 7). I suppose if that's the case, this feature could also be turned off in Gradle 7 in the meantime.

**Comment by chao2zhang** [comment]
My reproduction is on Gradle 6.8.3 and if I remember correctly, task dependency inferral based on output/input path was there a long time ago (https://blog.gradle.org/introducing-incremental-build-support#inferring-task-dependencies).

I would propose to simply reverting the change for now and rethink the implementation when AGP 7.0 comes out (Hopefully in the next 4 weeks or so).

**Comment by damianw** [comment]
Hm, alright, my misunderstanding then. Thanks for looking into it and apologies for the issues. I'll also look into this again when I have some time.

**Comment by cortinico** [comment]
@brentwatson Can you give it a try with `1.18.0-RC2` and confirm that the issue is not there anymore?

**Comment by brentwatson** [comment]
Sorry for the delay. I'm traveling this week and will be able to test out
RC2 next week when I'm back.

**Comment by brentwatson** [comment]
@cortinico -- I'm finally able to test with RC2. Just confirming that this is indeed resolved. Thanks!

```bash
❯ du -hs .
 14G	.

❯ ./gradlew detektBaselineMain detektBaselineTest
BUILD SUCCESSFUL in 1h 50m 14s
12105 actionable tasks: 6843 executed, 1719 from cache, 3543 up-to-date

❯ du -hs .
 45G	.
...
