### ISSUE TITLE
Publish the cli-all artifact to maven central

### ISSUE THREAD

**Issue by BraisGabin** [detekt/detekt#3969]
@BraisGabin Can we revisit this and continue publishing the cli-all artifact? At Uber, We've noticed that the -cli artifact was no longer published recently. This has caused an issue in upgrading detekt, since our toolchain requires a pull through maven central via our artifactory mirror.

This is done for a few reasons. Security, scans on artifacts be mirrored and verification of signatures. Redundancy in the case of issues in other hosts. Immutability, in the case that an artifact is changed in Github. This is standard for some other artifacts that need CLI access, like Gogle Java Format and Ktfmt.

_Originally posted by @tyvsmith in https://github.com/detekt/detekt/issues/3329#issuecomment-885843894_

**Comment by BraisGabin** [comment]
I did a git bisect and find out that this change was introduced in #3747. I don't understand the reason behind that PR so I can't help more here.

If someone is interested I used this script to automatice the bisect:
```shell
rm -rf ~/.m2 && ./gradlew :detekt-cli:publishToMavenLocal && find ~/.m2 -name "detekt-cli-*-all*" | grep -q "."
```

**Comment by 3flex** [comment]
#3574 updated Shadow to 6.1.0 (from 5.2.0). One change was "Support for Gradle Metadata publication via the shadowRuntimeElements configuration."

This led to https://github.com/detekt/detekt/pull/3738, though the underlying cause was https://github.com/detekt/detekt/issues/3743. To stop multiple variants being published and ending up in the Gradle metadata, https://github.com/detekt/detekt/pull/3747 was merged, which fixed the metadata issue but also stopped publication of the -all variant to Maven Central.

This can be fixed by adding the shadow JAR artifact to the Maven publication. PR incoming.
