### ISSUE TITLE
issue with Gradle 7+ org.gradle.api.InvalidUserCodeException: Cannot run Project.afterEvaluate(Action) when the project is already evaluated

### ISSUE THREAD

**Issue by dmitryskorbovenko** [detekt/detekt#4008]
https://github.com/detekt/detekt/blob/537459cd51ad79f87c5af19e766c44a0516d3734/detekt-gradle-plugin/src/main/kotlin/io/gitlab/arturbosch/detekt/internal/DetektAndroid.kt#L70

org.gradle.api.InvalidUserCodeException: Cannot run Project.afterEvaluate(Action) when the project is already evaluated

**Comment by cortinico** [comment]
Can you please provide more information (ideally fill the issue template)?

**Comment by 3flex** [comment]
We'll need more information to investigate the issue.

I suspect it's due to how the plugin is being applied in your build scripts. Behaviour changed in Gradle 7, see https://docs.gradle.org/7.0/userguide/upgrading_version_6.html#calling_project_afterevaluate_after_project_evaluation_is_now_an_error

The detekt plugin uses `afterEvaluate` at configuration time, so I strongly suspect the issue is something specific to your setup.

If you can provide more information we may be able to assist further - please reopen in that case.
