### ISSUE TITLE
excludes missing from JSON schema for style checks (maybe others too)

### ISSUE THREAD

**Issue by TWiStErRob** [detekt/detekt#4155]
## Expected Behavior
`excludes` show up in auto-complete for `stlye:` group checks too.

## Observed Behavior
![image](https://user-images.githubusercontent.com/2906988/135772017-59df1b2c-3a01-41bb-b00f-bd5011607afa.png)

## Steps to Reproduce
Create `detekt.yml` with contents:
```yml
style:
  UnusedPrivateClass:
    |
```
put cursor at `|` and press Cltr+Space (or equivalent).

## Context
The JSON schema is extremely helpful, please make it a full feature of Detekt. It's so easy to edit the configuration with it, but if I can't trust it shows me all the options it's not helpful.
`excludes` for example works for `style:` checks too, but not suggested.

**Comment by TWiStErRob** [comment]
Tip: you can inherit types in schemas, so you only need to define "active" and "excludes" once, and inherit each object from it.

**Comment by chao2zhang** [comment]
The JSON schema currently requires a manual PR to be approved in https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/detekt.json which is probably something we shouldn't wait for releasing detekt.

@3flex do you have ideas on automating this further since you had a discussion in https://github.com/SchemaStore/schemastore/pull/1301

@TWiStErRob I think we can do a one-time update regardless. Do you have time to contribute a PR in https://github.com/SchemaStore/schemastore/?

**Comment by 3flex** [comment]
> @3flex do you have ideas on automating this

Probably building on the detekt generator task so it also generates the schema, then publishing it using GitHub docs, using self hosting schema: https://github.com/SchemaStore/schemastore/blob/master/CONTRIBUTING.md#self-hosting-schemas

**Comment by BraisGabin** [comment]
That would help a lot with the discoberability of #4068.

I'd vote to create an issue (or "refactor" this one) to create our own schema.

**Comment by TWiStErRob** [comment]
Note: even if there's an automatic tool to generate the schema, I think it's ok to have a manual upload at first, it's ok to have a delay of their approval on the schema store. It's not going to block your release, but also would get up to date and precise schema to users.

**Comment by BraisGabin** [comment]
Ok, I'm going to create a new issue to track the creation of our own schema. 

> @TWiStErRob I think we can do a one-time update regardless. Do you have time to contribute a PR in https://github.com/SchemaStore/schemastore/?

Meanwhile it's out of our scope to fix this. You can contribute to `SchemaStore` directly to fix it. I'm closing this one because there is not action that we can do in this repo to fix it. Anyway, don't hestiate to write here if you need any help making a PR to `SchemaStore`.
