### ISSUE TITLE
Duplicate rules - `MaximumLineLength` & `MaxLineLength`

### ISSUE THREAD

**Issue by Michael-MF** [detekt/detekt#4182]
I believe the following rules are duplicates of each other:
* [MaximumLineLength](https://detekt.github.io/detekt/formatting.html#maximumlinelength) under the `formatting` rule set
* [MaxLineLength](https://detekt.github.io/detekt/style.html#maxlinelength) under the `style` rule set

**Comment by BraisGabin** [comment]
They do the same. But the first one is a rule from ktlint. And you need to add the plugin for it. The second is a a detekt rule and you don't need to add any plugin. We could remove the one from ktlint but that one have autocorrect, a thing that the one from detekt doesn't have. But removing the one from detekt doesn't seems like a good idea either because we don't want to force anyone to use the formatting plugin.

**Comment by BraisGabin** [comment]
I'd set that comment only in `MaximumLineLength` because is the one that is in the plugin. `MaxLineLength` can't know about the other. But, yes please, go ahead and raise a PR :)

Maybe the message could be something like: "This rules overlaps with `MaxLineLength` from the standard rules, make sure to enable just one or keep them aligned".
