### ISSUE TITLE
`SwallowedException` even when the exception is logged

### ISSUE THREAD

**Issue by fzyzcjy** [detekt/detekt#4547]
Hi thanks for the lib! I see `SwallowedException` even when the exception is logged.

Example code snippet:

            } catch (e: BizException) {
                log.debug("sendVerifySms see BizException", e)
                throw BizException(e.presentMessage + somethingelse)
            }

**Comment by BraisGabin** [comment]
I'm not sure if this is a false-positive. Shouldn't it be better do something like this?:

```kotlin
        } catch (e: BizException) {
            log.debug("sendVerifySms see BizException", e)
            throw BizException(e.presentMessage + somethingelse, e)
        }
```

**Comment by fzyzcjy** [comment]
Hmm `BizException` is business exception and I indeed do not care about its stack, only care about its message. So should we use that `e` - will it cause extra performance penalty?

**Comment by BraisGabin** [comment]
Yeah, I see your point. But that's exactly what a shallow an exception is. You aren't passing the root cause, you are "sallow"ing it.

In general, shallowing an exception is a bad practice. But there are cases where it can have sense, so maybe this is a god place to add `@Suppress("ShallowException")`.

About the performance penalty: it is negligible. And, in general, detekt doesn't aim to performant code. It aims to maintainable code.

**Comment by fzyzcjy** [comment]
> But that's exactly a shallow exception. You aren't passing the root cause, you are "sallow"ing it.

I logged it so stack traces are there. Is it ok?

> About the performance penalty: it is negligible. And, in general, detekt doesn't aim to performant code. It aims to maintainable code.

I agree.

**Comment by BraisGabin** [comment]
The rule is doing what it is meant to do. If you are rethrowing another excetion you should add the exception as a cause so upper catch could know why that error happened. But, if you don't rethrow the rule is ok just with you logging it.

**Comment by fzyzcjy** [comment]
Ok thank you!
