### ISSUE TITLE
Add rule to check if Flow collected

### ISSUE THREAD

**Issue by osipxd** [detekt/detekt#4640]
## Expected Behavior of the rule

```kotlin
val profileFlow: Flow<Profile> = ...

fun observeProfile() {
    profileFlow.onEach { ... } // FlowNotCollected: launchIn, collect or another function is not called
}

fun observeProfile(): Flow<ProfileUi>  {
    return profileFlow.onEach { ... } // Ok: Flow is not collected but returned from function
}
```

## Context

It would be nice to catch cases when flow is not collected because:
1. It is quite easy to forget to collect flow, or you can use `onEach` instead of `collect` by mistake.
2. Even if you never forget to collect flow you can mess with this issue after refactoring:
    Imagine you want to migrate some function from suspend to flow:
    ```diff
    -suspend fun refreshProfile() { ... }
    +fun refreshProfile(): Flow<RefreshState> { ... }
    ```
    After this change all methods used `refreshProfile` become broken because returned flow is not collected.

**Comment by BraisGabin** [comment]
>     1. It is quite easy to forget to collect flow, or you can use `onEach` instead of `collect` by mistake.

I agree with the idea of your rul but I'm not sure how to implement it. The problem is that there are function in frameworks that work as `collect` for example `collectAsState` from Compose.

>     2. Even if you never forget to collect flow you can mess with this issue after refactoring:
>        Imagine you want to migrate some function from suspend to flow:
>        ```diff
>        -suspend fun refreshProfile() { ... }
>        +fun refreshProfile(): Flow<RefreshState> { ... }
>        ```   
>        After this change all methods used `refreshProfile` become broken because returned flow is not collected.

We have `IgnoredReturnValue` rule exactly for that, you just need to anotate your function with `@CheckResult`

-----

I have an idea to reformulate this rule. There are some types that are designed to be consumed. They have no sense if they are not cosumed once they are returned by a function. For example, `Flow.onEach` returns a `Flow` and if you don't do something with it the call to `onEach` is completely pointless.

My idea: We could extend `IgnoredReturnValue` and make it receive a list of types from the configuration. The rule will flag any call to a function that returns one of those types if the returned is ignored.

If we implement that then you should only need to add `kotlinx.coroutines.flow.Flow` to that list. We could even consider adding it as a default value.

What do you think? Would that work for your use cases?

**Comment by osipxd** [comment]
>The problem is that there are function in frameworks that work as `collect` for example `collectAsState` from Compose.

Maybe if extension function on `Flow` is not returning `Flow`, consider it as a "terminal"?
 
> My idea: We could extend `IgnoredReturnValue` and make it receive a list of types from the configuration. The rule will flag any call to a function that returns one of those types if the returned is ignored.
> 
> If we implement that then you should only need to add `kotlinx.coroutines.flow.Flow` to that list. We could even consider adding it as a default value.

This sounds great! I think this rule should cover both use cases I mentioned.

**Comment by osipxd** [comment]
> Do you want to give it a try?

Yes, I'll try to implement it

**Comment by BraisGabin** [comment]
Don't hesitate to ask if you need help ;)

**Comment by gouri-panda** [comment]
@osipxd Are you planning on resuming your work?

**Comment by osipxd** [comment]
@gouri-panda, thanks for reminding! Yes, I'm planning to finish it on this week
