### ISSUE TITLE
JVM 17 & Kotlin 1.6.x Support

### ISSUE THREAD

**Issue by Nitewriter** [detekt/detekt#4786]
The changes made to the final version of 1.20.0 have reverted fixes that addressed the `invalid jvm target` error experienced in this ticket. https://github.com/detekt/detekt/issues/4287

```bash
* What went wrong:
Execution failed for task ':match-api:detekt'.
> Invalid value passed to --jvm-target
```

I'm currently unable to upgrade to resolve the current `XML External Entity (XXE) Injection` vulnerability. Version 1.20.0-RC2 continues to have no issues with JVM 17 and Kotlin 1.6.x, but does not have a resolution for the vulnerability.

**Comment by cortinico** [comment]
> The changes made to the final version of 1.20.0 have reverted fixes that addressed the `invalid jvm target` error experienced in this ticket. #4287

Could you link to the revert you're talking about?

**Comment by mkaulfers** [comment]
@cortinico this is the ticket he's referring to that should have fixed it, but it is no longer working. #4277

**Comment by rocketraman** [comment]
Is there a workaround, or do we need to revert to 1.19 for now?

**Comment by cortinico** [comment]
How are you folks passing the `--jvm-target`? Via CLI or via Gradle? Which value are you specifying? 
Could you provide a reproducer of any form to help us understand what's going on?

**Comment by rocketraman** [comment]
In my case I'm using the gradle plugin. I am not passing that argument explicitly at all.

**Comment by cortinico** [comment]
> In my case I'm using the gradle plugin. I am not passing that argument explicitly at all.

I'm not able to reproduce. Tested with:

``` 
$ java -version
openjdk version "17.0.2" 2022-01-18 LTS
OpenJDK Runtime Environment Zulu17.32+13-CA (build 17.0.2+8-LTS)
OpenJDK 64-Bit Server VM Zulu17.32+13-CA (build 17.0.2+8-LTS, mixed mode, sharing)
```

Running `./gradlew detetkMain` without specifying `--jvm-target` leads to a successful build.

**Comment by rocketraman** [comment]
I use gradle toolchains configuration in my build. Maybe that's causing a problem?

**Comment by rocketraman** [comment]
Seems like the problem might be this declaration in my Gradle build:

```
tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile>().configureEach {
  kotlinOptions {
    jvmTarget = JavaVersion.VERSION_11.toString()
  }
}
```

It also doesn't seem to matter which version is actually specified -- detekt bails in any case.

**Comment by cortinico** [comment]
> jvmTarget = JavaVersion.VERSION_11.toString()

That should work. Could you try with just "11" or with `JvmTarget.JVM_11`?
Also @3flex do you have some context here as you introduced the `JvmTargetConverter`?

**Comment by rocketraman** [comment]
> That should work. Could you try with just "11" or with `JvmTarget.JVM_11`?

The output of `JavaVersion.VERSION_11.toString()` is already "11" but I tried it anyway, and as expected, the same error results.

**Comment by rocketraman** [comment]
Thanks for the hint @cortinico on `JvmTargetConverter`... I added a debugger to `DetektInvoker`. Assuming I'm looking at the right place, I see that my build does not pass a `--jvm-target` option at all. 

Looking at the code at https://github.com/detekt/detekt/blob/main/detekt-cli/src/main/kotlin/io/gitlab/arturbosch/detekt/cli/ArgumentConverters.kt#L54-L57, it looks like this code assumes that `--jvm-target` is a required argument.

I now see also in the README at https://github.com/detekt/detekt#with-gradle it does actually specify that the jvm target needs to be set explicitly for Detekt -- this appears to be new in 1.20 and was not called out in the migration guide at all.

I'm wondering if the plugin can simply use the JVM target from the Kotlin compiler options rather than having to inject this value separately.

**Comment by cortinico** [comment]
Thanks for looking into this @rocketraman 
Yes, it's a required argument but it has a default specified, if you don't specify any:

https://github.com/detekt/detekt/blob/16bbc16da0b9438d6f4fcf7a861cac9875817be7/detekt-cli/src/main/kotlin/io/gitlab/arturbosch/detekt/cli/CliArgs.kt#L189-L195

**Comment by rocketraman** [comment]
I assumed when I wrote my previous message that adding the explicit `jvmTarget` configuration for the Gradle plugin would fix the problem, but nope.

Debugging further, I think I see the problem... the `CompilerSpec` generated by the CLI invoker tooling is setting the `jvmTarget` value to "JVM_11", which is the toString value of the `JvmTarget` enum. It's this "JVM_" value that is causing the problem.

**Comment by rocketraman** [comment]
The failure seems to be at this line:

```
val filesToAnalyze = measure(Phase.Parsing) { parsingStrategy.invoke(settings) }
```

in the `Lifecycle` interface.

**Comment by rocketraman** [comment]
More specifically, `EnvironmentFacade.environment` calls `createCompilerConfiguration`, which a parameter: `compilerSpec.parseJvmTarget()`.

This `JvmTarget.fromString(jvmTarget)` on the `toString` output of `JvmTarget` is invalid i.e.

```
JvmTarget.fromString(JvmTarget.JVM_11.toString) == null
```

**Comment by rocketraman** [comment]
I submitted a PR https://github.com/detekt/detekt/pull/4800 to hopefully fix this. I haven't tested this TBH but it does compile.

**Comment by cortinico** [comment]
I'd like @3flex to take a look here and eventually revert https://github.com/detekt/detekt/pull/4694 if needed.

**Comment by 3flex** [comment]
I've added some new tests in #4801. Strings are mapped from Gradle plugin and parsed correctly by the CLI.

I'm not sure what I'm missing here, so a full reproducer will be helpful, but I will continue investigating in the meantime.

**Comment by 3flex** [comment]
What could be the problem is if `JvmTarget.JVM_11.toString()` is called from Gradle, and an older version of Kotlin is on Gradle's classpath, it will return "JVM_11", because Gradle embeds an earlier version of Kotlin which doesn't have the new `toString()` override on `JvmTarget` that detekt CLI relies on.

It should work if you just set `jvmTarget = "11"` in the build file, or `jvmTarget = JavaVersion.JVM_11.toString()`, and don't use `JvmTarget.JVM_11.toString()`.

**Comment by rocketraman** [comment]
> What could be the problem is if JvmTarget.JVM_11.toString() is called from Gradle, and an older version of Kotlin is on Gradle's classpath, it will return "JVM_11", because Gradle embeds an earlier version of Kotlin which doesn't have the new toString() override on JvmTarget that detekt CLI relies on.

I was on Gradle 7.3.3. I updated to 7.4.2 to check if that was the issue. Same problem with both versions. There should be no change in the version of Kotlin on the classpath -- I have no local customizations in this regard. Gradle uses whatever it uses, my build uses 1.6.10.

> It should work if you just set `jvmTarget = "11"` in the build file, or `jvmTarget = JavaVersion.JVM_11.toString()`, and don't use `JvmTarget.JVM_11.toString()` in build files.

No this does not work. In fact, I've never had `JvmTarget.JVM_11.toString()` in any of my build files. The call to `JvmTarget.JVM_11.toString()` is happening later in Detekt inside `Spec.kt`.

I'm not sure why all of these conversions from JvmTarget to and from Strings are going on. If you look at PR https://github.com/detekt/detekt/pull/4800 I submitted earlier, eventually you need to pass a `JvmTarget`, so why not just remove the multiple back-and-forths between JvmTarget and Strings and just keep the parsed `JvmTarget` value all the way through?

**Comment by 3flex** [comment]
Please provide a reproducer and we can hopefully narrow down exactly what's going on.

**Comment by 3flex** [comment]
A build scan may also help.

**Comment by rocketraman** [comment]
The reproducer is nothing special. Its I believe the most basic possible setup: https://github.com/rocketraman/test-detekt-4786.

```
./gradlew --version

------------------------------------------------------------
Gradle 7.4.2
------------------------------------------------------------

Build time:   2022-03-31 15:25:29 UTC
Revision:     540473b8118064efcc264694cbcaa4b677f61041

Kotlin:       1.5.31
Groovy:       3.0.9
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          17.0.3 (Oracle Corporation 17.0.3+8-LTS-111)
OS:           Linux 5.16.20-200.fc35.x86_64 amd64

$ ./gradlew detekt
> Task :detekt FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':detekt'.
> Invalid value passed to --jvm-target

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 696ms
1 actionable task: 1 executed
```

Here is the build scan: https://scans.gradle.com/s/3okubnbhzpsb4

**Comment by rocketraman** [comment]
If you saw an earlier email from me due to a comment on this issue, please ignore it -- I thought I had created a reproducer but it was a silly mistake on my part. So far I'm not having any luck with the reproducer.

I'll continue trying to reproduce for a bit, but I'm not sure how much longer I can spend on this. I'm happy to jump on a meeting to debug this together.

**Comment by rocketraman** [comment]
I finally reproduced it... here is the repro repository: https://github.com/rocketraman/test-detekt-4786.

Looks like this particular block in my gradle build is the source of the problem: https://github.com/rocketraman/test-detekt-4786/blob/master/build.gradle.kts#L13-L21.

I normally do this in my builds to ensure that my chosen version of Kotlin is used everywhere in my build.

**Comment by rocketraman** [comment]
It looks like that block is pulling in the 1.6.10 version of kotlin-compiler-embeddable whereas detekt is expecting the 1.6.20 version.

Build scan with invalid target:

https://scans.gradle.com/s/xhnopmleir2au/dependencies?dependencies=kotlin-compiler-embeddable&expandAll

Build scan with working detekt:

https://scans.gradle.com/s/ctcsi2vahsa7o/dependencies?dependencies=kotlin-compiler-embeddable&expandAll

Take a look at the detekt dependencies for kotlin-compiler-embeddable.

**Comment by 3flex** [comment]
> It looks like that block is pulling in the 1.6.10 version of kotlin-compiler-embeddable whereas detekt is expecting the 1.6.20 version.

That's exactly what's happening - detekt uses the "detekt" configuration to manage the Gradle plugin's dependencies, which would normally be pulling in detekt-cli 1.20.0 and kotlin-compiler-embeddable 1.6.20 (or 1.6.21, can't recall which we shipped with).

When you override all configurations you're also overriding the "detekt" configuration, overriding the expected kotlin-compiler-embeddable version.

You can do this instead: `configurations.matching { it.name != "detekt" }.all {`

I've tested on your repo and it fixes the issue.

**Comment by 3flex** [comment]
@Nitewriter I'm conscious that you might have a different root cause - or is this enough info to resolve your issue as well?

**Comment by rocketraman** [comment]
> When you override all configurations you're also overriding the "detekt" configuration, overriding the expected kotlin-compiler-embeddable version.

Is it correct for detekt to be tied so strongly to a particular kotlin version? And even if yes, then should detekt fail in such an esoteric way if that constraint is not met?

**Comment by 3flex** [comment]
> Is it correct for detekt to be tied so strongly to a particular kotlin version?

Yes. detekt utilises internal compiler code for its analysis. There's no public API as such so we don't have much choice here. Some updates to Kotlin are breaking for detekt so maintaining compatibility with multiple Kotlin versions isn't realistic.

> should detekt fail in such an esoteric way if that constraint is not met?

I think that's debateable. In your case it's a build configuration issue, and we can't account for everything that someone might do in their own build files when they inadvertently override the behaviour of the detekt Gradle plugin. We can't lock the specific Kotlin compiler version in the Gradle plugin either, because users can choose different detekt-cli versions and apply to the "detekt" configuration. A warning might be feasible, PR welcome.

**Comment by rocketraman** [comment]
> I think that's debateable. In your case it's a build configuration issue, and we can't account for everything that someone might do in their own build files when they inadvertently override the behaviour of the detekt Gradle plugin.

There is no need to account for "everything that someone might do". There should be a need to account for fundamental constraints of detekt being violated and report on that accordingly.

If this statement is true (it may be, but not really in this case -- the error condition in question was not anything fundamental with the compiler here, but rather the code relying on a specific version's behavior related to an ancillary function like `JvmTarget.toString()` which could be handled in a different way that would work across versions i.e. avoid converting from String -> JvmTarget -> String -> JvmTarget which is brittle by nature):

> Yes. detekt utilises internal compiler code for its analysis. There's no public API as such so we don't have much choice here. Some updates to Kotlin are breaking for detekt so maintaining compatibility with multiple Kotlin versions isn't realistic.

Then Detekt should do everything possible to ensure that this constraint is actually met, and if it is not (regardless of what esoteric condition caused the constraint failure), then it should warn with a message like:

"Detekt requires Kotlin compiler version 1.6.20 for analysis. Detekt is currently running with Kotlin compiler version x.x.x. Check the Detekt configuration."

instead of a message like:

"Invalid --jvm-target value"

> A warning might be feasible, PR welcome.

I've spent way more time on this issue already than I can justify -- might as well spend a bit more :-) Maybe I'll get to this. Pointers/guidance welcome.

**Comment by rocketraman** [comment]
BTW, other libraries that depend on specific compiler versions, like Compose, have just such logic in them. Compose will fail in the presence of the wrong Kotlin version, unless a specific setting is used to override that check.

Furthermore, IIRC Compose uses the version of Kotlin in the project and requires that to match the version expected by Compose -- it doesn't try to bring in its own version and use that, regardless of the version selected by the user. It seems the approach of selecting a compiler version which may not match the user's selected version is bound to cause other problems.

**Comment by BraisGabin** [comment]
I'm using JDK11, detekt 1.20.0 and kotlin 1.6.10 and all works perfect so this is a bit more complex. I mean, detekt right now works on other versions of kotlin too.

**Comment by 3flex** [comment]
See https://github.com/detekt/detekt/issues/4786#issuecomment-1116722049

We have the root cause and a fix for that issue, but I'm not sure if the original reporter has a different issue.

**Comment by itd-pal** [comment]
> You can do this instead: `configurations.matching { it.name != "detekt" }.all {`

@3flex 
I'm new to detekt so would it be possible to create an share a pull request on the repodruced repo where to add this change ?

Thanks

**Comment by 3flex** [comment]
@itd-pal I think that would be better raised in a separate support request, thanks! Try https://github.com/detekt/detekt/discussions

**Comment by itd-pal** [comment]
I opened #4813 @3flex

**Comment by cortinico** [comment]
> @itd-pal I think that would be better raised in a separate support request, thanks! Try [detekt/detekt/discussions](https://github.com/detekt/detekt/discussions)

Should we close this issue then?

**Comment by itd-pal** [comment]
FYI 
For me it fixed the problem by updating either 
detekt to `1.20.0-RC2` with kotlin `1.6.10` 
or updating kotlin to `1.6.20` and detekt `1.20.0`
