### ISSUE TITLE
MagicStrings (hardcoded text)

### ISSUE THREAD

**Issue by notaLonelyDay** [detekt/detekt#4991]
The rule or changes you're looking for might have already been suggested!
Please search in the [issues](https://github.com/detekt/detekt/issues) before creating a new one.

## Expected Behavior of the rule

It works like magic numbers, but for strings
## Context

For the same reasons we have magic numbers

**Comment by cortinico** [comment]
> For the same reasons we have magic numbers

I don't know how to feel about this. Numbers doesn't necessary carry a meaning by itself, while strings might (i.e. their content is often self-explanatory).

**Comment by notaLonelyDay** [comment]
> their content is often self-explanatory
Maybe their content is, but sometimes extracting strings to variables helps reading and maintaining code

**Comment by marschwar** [comment]
I agree with @cortinico. Unless there is a very kind of magic string that should always be extracted to a constant, I do not see much value in such a rule. Do you have anything specific in mind?

**Comment by BraisGabin** [comment]
+1, magic number is the rule with more configurations on the project because it's really difficult to maintain because it have lots of false positives.

I can imagine a rule related with Android and some of their apis: `Bundle`, `SharedPreferences`... But I don't think that something like this should be in the default rule sets because they are framework specific.

**Comment by BraisGabin** [comment]
I'm closing this as it seems that we don't want a rule like this inside the main rule set. Remember that you always can write this rule for yourself or, even better"open source it so anyone could use it too.
