### ISSUE TITLE
Deprecate ignoreOverridden in name rules

### ISSUE THREAD

**Issue by BraisGabin** [detekt/detekt#5600]
The rules:

- BooleanPropertyNaming
- ConstructorParameterNaming
- FunctionNaming
- VariableNaming

Have the ignoreOverridden configuration flag but it have really little sense. There's nothing you can do about those names. So it should not be a configuration. It should be by default in all those rules. 

So my proposal is to deprecate those configurations to simplify a bit our configuration that is long enough. We should also include the ones that will be included with #5590

There are also two other rules were I don't have it so clear:

- `FunctionParameterNaming`: in this case you can rename them but that's a really bad idea. So deprecate it and always ignore deprecate seems like a sane decission. 
- ~`MemberNameEqualsClassName`: I don't fully understand how this rule could help my code. But I imagine that keep it here have sense. Because in this one you can act on the issue. You can change the name of the class.~

**Comment by TWiStErRob** [comment]
Agree with top 4. Also with `FunctionParameterNaming`. I would keep for `MemberNameEqualsClassName` because in that case you have control over the class name at least if you choose to disable the flag.

> `MemberNameEqualsClassName` I don't fully understand how this rule could help my code.

It helps with Java migration (in people's brains) to not accidentally create `class Foo { fun Foo() }` thinking it's a constructor, and additionally it helps when your action in the class is the same as the name, which is almost never the same word, so for `class Generator { fun generator() }` you get a flag to rename it, and hopefully do `fun generate()` instead. So essentially simple sanity checks similar to min-max naming.

**Comment by BraisGabin** [comment]
Ok let's forget about `MemberNameEqualsClassName`. This PR is ready to grab. Remove the `ignoreOverridden` flag from those rules. The rule should behaves as that flag was always on.
