### ISSUE TITLE
ignoreAnnotated not working with complexity>TooManyFunctions

### ISSUE THREAD

**Issue by mukeshsolanki** [detekt/detekt#5744]
## Expected Behavior
The annotations mentioned in ignoreAnnotated should not be counted towards TooManyFunctions.

## Observed Behavior
The methods that have been annotated with the annotation to ignore is also getting added.

## Steps to Reproduce
1. Create an annotation.
2. Added the annotation to the ignoreAnnotated under TooManyFunctions
3. Add more functions than the limit in the class.

## Context
We want to limit the business logic and the number of functions being created in the ViewModel. But we also have a few analytic events in the ViewModel. We don't want to count these analytic events towards the functions that are actually containing any business logic.

## Your Environment
* Version of detekt used: 1.22.0
* Version of Gradle used (if applicable): 7.4.0
* Gradle scan link (add `--scan` option when running the gradle task):
* Operating System and version: Mac OS 13
* Link to your project (if it's a public repository): Not public but sharing a zip of the sample codebase where the issue can be reproduced. FYI using Android Studio.
[TestApp.zip](https://github.com/detekt/detekt/files/10567547/TestApp.zip)

**Comment by BraisGabin** [comment]
That's not what `ignoreAnnotated` does. To make it work you should annotate the class and it will just ignore the issue.

We could create a new configuration on `TooManyFunctions` so it doesn't count certain functions.

But I'm not 100% sure if we want to add something like that. It seems like a edge case to me. Something that could be done by creating a custom rule instead of adding it to the default rule set. I would like to know what other people think about this.
