### ISSUE TITLE
Add docs for enabling Worker API in Gradle plugin

### ISSUE THREAD

**Issue by 3flex** [detekt/detekt#5843]
Docs for #4128

**Comment by cortinico** [comment]
Can we get this in the near future as the docs should be included in 1.23 once is out

**Comment by atulgpt** [comment]
Hi, @3flex do we want to mention that worker API can be enabled in detekt in the doc? Or do we also want to add reasoning behind that decision? 

Since this is optional right now and I think it will be the default in future(correct me if I am wrong here) then are we expecting some feedback from users when worker API is enabled? 

Also, should we warn users if enabling this can cause some issues in analysis? Maybe corrupt Gradle daemon, more time in running detekt? Or do we want to make this flag(`detekt.use.worker.api`) experimental as of now?

Answering these will help to close this issue

**Comment by BraisGabin** [comment]
I think that our greatest concern is performance. We don't know if it will make detrkt faster because we have better parallelism or it will be slower because we need to load a lot of classes each time that without this they are shared.

I think that a first draft just explaining how to enable it and what does it brings is enough for now. They don't need to go too deep. Some link to the gradle documentation would make all of it shorter.

**Comment by atulgpt** [comment]
Hi, @BraisGabin is there any website section which lists `Gradle` properties configs? Right now there is one for `Gradle` `detekt` closure at https://detekt.dev/docs/gettingstarted/gradle#options-for-detekt-configuration-closure. Do you want to create one below `options-for-detekt-configuration-closure` with the name of `options-for-detekt-gradle-property`?

**Comment by cortinico** [comment]
I would suggest to create a section here https://detekt.dev/docs/gettingstarted/gradle
