### ISSUE TITLE
Update `allRules` flag to just be `experimentalRules`

### ISSUE THREAD

**Issue by ColtonIdle** [detekt/detekt#5920]
allRules is set to false by default. As someone new to detekt... that doesn't make sense. Of course I want allRules on?

If I check the docs, allRules basically means to enable "unstable rules" and so maybe it's worth it to change its name to unstableRules or experimentalRules? It makes much more sense (to me at least) that those names would be = false by default

**Comment by cortinico** [comment]
> Of course I want allRules on?

Nope that's not always the case. Actually a lot of tools comes with a set of rules which are not enabled by default (Android Lint is doing the same).

We do have rules that we don't enable by default because they're either experimental, unstable, or just don't fit the majority of use cases (for example, those for library authors)

**Comment by schalkms** [comment]
As far as I remember, this was a design decision back then.

**Comment by ColtonIdle** [comment]
Interesting. Maybe some more clarity with allRules in the docs would be helpful as I found it kinda tough to figure out what it was for. Thanks for the info though! TIL
