### ISSUE TITLE
Links to ktlint rule documentation broken

### ISSUE THREAD

**Issue by marschwar** [detekt/detekt#6099]
Ktlint seems to have moved to versioned docs as well and therefor all links on https://detekt.dev/docs/rules/formatting pointing to the documentation of the wrapped rule are broken.

404 https://pinterest.github.io/ktlint/rules/standard/#annotation-formatting
200 https://pinterest.github.io/ktlint/0.49.0/rules/standard/#annotation-formatting
 
Additionally: Rules that were promoted from experimental to the standard ruleset [in version 0.49.0](https://github.com/pinterest/ktlint/releases/tag/0.49.0) still have a link to experimental (e.g. `FunctionStartOfBodySpacing` points to https://pinterest.github.io/ktlint/rules/experimental/#function-start-of-body-spacing).

**Comment by 3flex** [comment]
There's probably an easier way to fix this in the meantime, so it behaves like status quo, instead of keeping our links up to date to their versioned docs when we update ktlint.

Just add `/latest` to the path which redirects to the latest version: https://pinterest.github.io/ktlint/**latest**/rules/standard/#annotation-formatting

It does mean that our version of the docs won't point to the correct version of the ktlint docs, but at least it will be no worse than what we've done historically. And importantly it will fix the 404s.

**Comment by marschwar** [comment]
Do you mean as a quick fix for the 1.x?

IMO the pr is ready. See https://detekt-huhgq4jz9-detekt.vercel.app/docs/next/rules/formatting
