### ISSUE TITLE
Check `@Suppress`ed IDs in a case-insensitive manner

### ISSUE THREAD

**Issue by lwasyl** [detekt/detekt#6148]
Follow up to https://github.com/detekt/detekt/issues/6143 because it's pretty confusing to have to use specific case to suppress rules, more so if Kotlin suppresses the same inspection with different casing.

Is there any reason to only respect suppressed IDs exactly as Detekt defines them? Seems like at least in some context different cases are supported (https://github.com/detekt/detekt/blob/dcfb8415c3ae9864d9e25226faebd26713bdab90/detekt-api/src/main/kotlin/io/gitlab/arturbosch/detekt/api/internal/Suppressions.kt#L45)

**Comment by TWiStErRob** [comment]
`@Suppress("iTerATornOTthRowinGNosuCHelEMenTexCePtiOn")`?

I don't know the exact reason, but one I could easily say is Kotlin is a strongly typed case sensitive language, so tooling around it should also be strict.

So the rules (convention) are (as far as I seen so far):
 * Detekt rule names are whatever their issue ID is, which is usually the same as the `ClassName`.
 * There are some extra aliases added for deprecated/renamed rules so existing suppressions in the codebase don't need to be migrated.
 * There are some extra aliases added for rules which detect similar things that the compiler does. ([Kotlin compile errors and warnings are `ALL_UPPERCASE_WITH_UNDERSCORES`](https://github.com/JetBrains/kotlin/blob/master/compiler/frontend/src/org/jetbrains/kotlin/diagnostics/rendering/DefaultErrorMessages.java)), _but it looks like ["warnings" and potentially all-lowercase](https://github.com/JetBrains/kotlin/blob/master/compiler/frontend.common/src/org/jetbrains/kotlin/diagnostics/AbstractKotlinSuppressCache.kt#L93) is also accepted, but in all codebases and forums I've only ever seen all-uppercase and it would be confusing to see otherwise._
 * I think there are no extra aliases added for IntelliJ IDEA inspections, because they're tool specific.
 * There are some exceptional ones, like `all`, which are [historical from Java `-Xlint`](https://docs.oracle.com/en/java/javase/17/docs/specs/man/javac.html#option-Xlint-custom), funnily "all" only works for Detekt and Java, not Kotlin on IDEA. For this reason I would recommend using `@Suppress("Detekt.All")` in this case.

---

Note that the "unused" in #6143 is actually not suppressing a compiler warning and unused private function is not flagged by the Kotlin compiler:
```
private fun f(@Suppress("unused") param: Bar) {}
w: foo.kt:25:23 Parameter 'context' is never used
```
"unused" is a special one that comes from Java, and adopted by all "Unused*" rules, and all "Unused*" IntelliJ Inspections. Kotlin only has UNUSED_PARAMETER and others listed in [`DefaultErrorMessages`](https://github.com/JetBrains/kotlin/blob/master/compiler/frontend/src/org/jetbrains/kotlin/diagnostics/rendering/DefaultErrorMessages.java).  IntelliJ IDEA's "unused" inspection is actually coming from the Kotlin IntelliJ Plugin: https://github.com/JetBrains/intellij-community/blob/master/java/java-analysis-impl/src/com/intellij/codeInspection/unusedSymbol/UnusedSymbolLocalInspectionBase.java#L21, but that's also strictly lowercase.

**Comment by schalkms** [comment]
Good point!
Closed as not planned due to the arguments made by Rob.

**Comment by lwasyl** [comment]
I see, for some reason I mistakenly used `unused` as an example, but just to clarify

> one I could easily say is Kotlin is a strongly typed case sensitive language, so tooling around it should also be strict.

native Kotlin tooling is _not_ as strict: there are no compiler or IDE warnings for the following code:

```kotlin
@Suppress("uNuSeD_pArAMEtER")
fun x(unused: String) = Unit
```
will not show a warning either in IntelliJ or in compiler output

![image](https://github.com/detekt/detekt/assets/3951580/b944f788-9164-4beb-9b3a-95001823be6b)

![image](https://github.com/detekt/detekt/assets/3951580/15865b7d-6150-4c96-9dbd-05a8cfe07d2c)

Also 
> I think there are no extra aliases added for IntelliJ IDEA inspections, because they're tool specific.

I thought Intellij IDEA is pretty much _the_ IDE for Kotlin developers, and overall misalignment between Detekt and native tooling seems like not the most practical approach, but of course that's just feedback from one person :+1:
