### ISSUE TITLE
Fail lint for `error(throwable)`

### ISSUE THREAD

**Issue by WildOrangutan** [detekt/detekt#6979]
Using `error(throwable)` is kind of bad thing to do. It will result in `throw IllegalStateException(throwable.toString())`.

## Expected Behavior of the rule

Fail lint, if `error()` argument is of `Throwable` type.

**Comment by atulgpt** [comment]
Hi, @BraisGabin/ @WildOrangutan  I think we can add this in the forbidden method. So that using `error(throwable)` will be reported

**Comment by psuzn** [comment]
Been doing some poking around and the issue lies in `FunctionMatcher.WithParameters.match(CallableDescriptor)`, where it compares the `encounteredParamTypes` and `parameters`. 

<img width="850" alt="image" src="https://github.com/detekt/detekt/assets/19205305/eab420ac-f2df-4874-acee-4c555fd07e02">

 If we configure it to forbid method call `kotlin.error(kotlin.Throwable)` the produced: 
  - `encounteredParamTypes` is `[kotlin.Any]` and.
  - `parameters` is `[kotlin.Throwable]` 
  
and it is just doing a string comparison so it doesn't know both parameter types indicate the same function signature. 

We can check their types to verify if one is a supertype of another? would appreciate it if there is a better alternative.

**Comment by BraisGabin** [comment]
Thinking out loud. If I have this:

```kotlin
fun foo(any: Any){}
fun foo(number: Number){}
```

If now I forbid `foo(Any)` then a call like `foo(5)` would be forbidden? That shouldn't be the case. So I'm not sure if we can change this without breaking other things. Do you see a way to make it work? Then we can think about how to implement it and what we should use instead of `String`.

**Comment by BraisGabin** [comment]
The problem is a bit more complex than that. Even ignoring the problem I pointed out before. In the codebease you would have something like `foo(IllegalStateException())`. And you would forbid `foo(Throwable)`.

Also, I would like to know if there are more real use cases to something like this. This change is not going to be easy so, if there are more use cases to forbid something like this we could thing to implement it. Otherwise I would vote for an specific rule.

**Comment by psuzn** [comment]
We might be better off with a specific rule.
