### ISSUE TITLE
[Compiler Plugin] subsequent runs of compileKotlin does not trigger analysis

### ISSUE THREAD

**Issue by WebTiger89** [detekt/detekt#7587]
Running task `compileKotlin` in the first place prints analyzing result to console but following runs do not. It might be related to caching. I have _configuration cache_ und _build cache_ enabled. Running:

`compileKotlin --no-configuration-cache --rerun-tasks`

triggers the analysis again.

**Comment by 3flex** [comment]
At the moment this is by design.

Detekt compiler plugin reports issues as compiler warnings, so if the compilation is successful, it will be considered up to date by Gradle and won't run again unless the source changes.

You can upgrade compiler warnings to errors which will cause the compilation to rerun each time if detekt reports issues: https://stackoverflow.com/a/46244803
