### ISSUE TITLE
Gradle plugin should reference its custom configurations lazily

### ISSUE THREAD

**Issue by bmuschko** [detekt/detekt#7642]
## Expected Behavior

You will want to reference configurations using the [`named`](https://docs.gradle.org/current/javadoc/org/gradle/api/NamedDomainObjectCollection.html#named(java.lang.String)) method so that resolving dependencies are resolved lazily, optimally during Gradle's execution time.

> Locates a object by name, without triggering its creation or configuration, failing if there is no such object.

## Current Behavior

Configurations should be referenced lazily so that they won't be resolved right at that time of accessing it. The plugin references the `detekt` and `detektPlugins` configurations using the [`getAt`](https://docs.gradle.org/current/javadoc/org/gradle/api/artifacts/ConfigurationContainer.html#getAt(java.lang.String)) method. `getAt` is synonymous for the [`getByName`](https://docs.gradle.org/current/javadoc/org/gradle/api/artifacts/ConfigurationContainer.html#getByName(java.lang.String)) method which will resolve the dependencies right there and then.

- https://github.com/detekt/detekt/blob/main/detekt-gradle-plugin/src/main/kotlin/io/gitlab/arturbosch/detekt/DetektPlugin.kt#L108-L109
- https://github.com/detekt/detekt/blob/main/detekt-gradle-plugin/src/main/kotlin/io/gitlab/arturbosch/detekt/DetektPlugin.kt#L134-L135
- https://github.com/detekt/detekt/blob/main/detekt-gradle-plugin/src/main/kotlin/io/gitlab/arturbosch/detekt/DetektPlugin.kt#L139-L140

## Context

Avoid potentially resolving dependencies for the `detekt` and `detektPlugins` configurations during Gradle's configuration time.

**Comment by 3flex** [comment]
These calls are only included in `configureEach` blocks, meaning they're already called lazily and only when the task is created. They're not called when the task is registered during the configuration phase.

Have you seen this issue occur, where the dependencies download during configuration phase? If detekt tasks aren't being configured lazily it suggests there's a problem with your build where the tasks are being created eagerly which then triggers the configuration to be realised. You can probably improve the situation in your build by checking if detekt tasks are created lazily, and if not, find out why and try to address it.

This is just an FYI. I'll merge your PR since it should push the configuration to task execution in all cases even if the tasks are created eagerly.

**Comment by bmuschko** [comment]
This issue is occurring in a rather large project with hundreds of subproject in conjunction with Android functionality + a custom Detekt plugin which is added to the `detektPlugins` configuration. I'll try to see if I can create a reproducer in a much smaller, separate project. It's certainly possible that the task creation is triggered somewhere else in the project but I haven't found it yet. I am trying to get to the bottom of things and let you know.
